from _typeshed import Incomplete
from difflib import SequenceMatcher

def htmlEncode(s, esc=...): ...

commentRE: Incomplete
tagRE: Incomplete
headRE: Incomplete

class HTMLMatcher(SequenceMatcher):
    def __init__(self, source1, source2) -> None: ...
    def set_seq1(self, a) -> None: ...
    def set_seq2(self, b) -> None: ...
    def splitTags(self, t): ...
    def splitWords(self, t): ...
    def splitHTML(self, t): ...
    def htmlDiff(self, addStylesheet: bool = False): ...
    def textDelete(self, lst, out) -> None: ...
    def textInsert(self, lst, out) -> None: ...
    def stylesheet(self): ...
    def addStylesheet(self, html, ss): ...
    def startInsertText(self): ...
    def endInsertText(self): ...
    def startDeleteText(self): ...
    def endDeleteText(self): ...
    def formatInsertTag(self, tag): ...
    def formatDeleteTag(self, tag): ...

class NoTagHTMLMatcher(HTMLMatcher):
    def formatInsertTag(self, tag): ...
    def formatDeleteTag(self, tag): ...

def htmldiff(source1, source2, addStylesheet: bool = False):
    """
    Return the difference between two pieces of HTML

        >>> htmldiff(\'test1\', \'test2\')
        \'<span class="delete">test1 </span> <span class="insert">test2 </span> \'  # NOQA
        >>> htmldiff(\'test1\', \'test1\')
        \'test1 \'
        >>> htmldiff(\'<b>test1</b>\', \'<i>test1</i>\')
        \'<span class="tagDelete">delete: <tt>&lt;b&gt;</tt></span> <span class="tagInsert">insert: <tt>&lt;i&gt;</tt></span> <i> test1 <span class="tagDelete">delete: <tt>&lt;/b&gt;</tt></span> <span class="tagInsert">insert: <tt>&lt;/i&gt;</tt></span> </i> \'
    """

def diffFiles(f1, f2): ...

class SimpleHTMLMatcher(HTMLMatcher):
    """
    Like HTMLMatcher, but returns a simpler diff
    """
    def startInsertText(self): ...
    def endInsertText(self): ...
    def startDeleteText(self): ...
    def endDeleteText(self): ...
    def formatInsertTag(self, tag): ...
    def formatDeleteTag(self, tag): ...

def simplehtmldiff(source1, source2):
    """
    Simpler form of htmldiff; mostly for testing, like:

        >>> simplehtmldiff('test1', 'test2')
        '-[test1 ]+[test2 ]'
        >>> simplehtmldiff('<b>Hello world!</b>', '<i>Hello you!</i>')
        '-[<b>]+[<i>]<i> Hello -[world! ]-[</b>]+[you! ]+[</i>]</i> '
    """

class TextMatcher(HTMLMatcher):
    def set_seq1(self, a) -> None: ...
    def set_seq2(self, b) -> None: ...
    def htmlDiff(self, addStylesheet: bool = False): ...
    def writeLines(self, lines, out) -> None: ...
