from _typeshed import Incomplete
from collections.abc import Generator
from Products.Five.browser import BrowserView

class RegistrationsView(BrowserView):
    def getTemplateViewRegistrations(self, mangle: bool = True):
        """get all global view registrations and cycle through the local
        ones to see which views have already been customized ttw"""
    def getTemplateCodeFromRegistration(self): ...
    def getTemplateViewRegistrationInfo(self): ...
    def getRegistrationFromRequest(self): ...
    def registerTTWView(self, viewzpt, reg) -> None: ...
    def customizeTemplate(self) -> None: ...
    def getLocalRegistrations(self) -> Generator[Incomplete]: ...
