from _typeshed import Incomplete
from collections.abc import Generator

def getViews(type) -> Generator[Incomplete]:
    """get all view registrations (stolen from zope.app.apidoc.presentation),
    both global and those registered for a specific layer"""

def interfaceName(iface):
    """return a sensible name for the given interface"""

def templateViewRegistrations(): ...
def templateViewRegistrationInfos(
    regs, mangle: bool = True
) -> Generator[Incomplete]: ...
def templateViewRegistrationGroups(regs, mangle: bool = True): ...
def findTemplateViewRegistration(required, viewname): ...
def generateIdFromRegistration(reg): ...
def getViewClassFromRegistration(reg): ...
def getTemplateCodeFromRegistration(reg): ...
def getViewPermissionFromRegistration(reg): ...
def createTTWViewTemplate(reg): ...
def customizeTemplate(reg): ...
