from plone.app.iterate.base import BaseContentCopier

class ContentCopier(BaseContentCopier):
    def copyTo(self, container): ...
    def merge(self): ...
    def checkin(self, checkin_message): ...

class FolderishContentCopier(ContentCopier): ...

def update_relation_catalog(obj) -> None: ...
