from plone.app.iterate.base import CheckinCheckoutBasePolicyAdapter

class CheckinCheckoutPolicyAdapter(CheckinCheckoutBasePolicyAdapter):
    """
    Dexterity Checkin Checkout Policy
    """
    def checkin(self, checkin_message): ...
    def getBaseline(self): ...
    def getWorkingCopy(self): ...
    def getProperties(self, obj, default=None): ...
