from _typeshed import Incomplete
from plone.restapi.services import Service

class UsersPost(Service):
    """Creates a new user."""

    params: Incomplete
    def __init__(self, context, request) -> None: ...
    def publishTraverse(self, request, name): ...
    def translate(self, msgid): ...
    def translate_fieldname(self, fieldname):
        """Not all fields that appear on Add User Form in Volto match in Plone."""
    def validate_input_data(self, portal, original_data) -> None:
        """Returns a tuple of (required_fields, allowed_fields)"""
    def add_field_error(self, field, msgid) -> None: ...
    def errors_to_string(self): ...
    errors: Incomplete
    def reply(self): ...
    @property
    def can_manage_users(self): ...
    @property
    def can_set_own_password(self): ...
    @property
    def can_add_member(self): ...
    def update_password(self, data): ...
