from _typeshed import Incomplete
from plone.namedfile.browser import ALLOWED_INLINE_MIMETYPES
from plone.namedfile.browser import DISALLOWED_INLINE_MIMETYPES
from plone.namedfile.browser import USE_DENYLIST
from plone.restapi.services import Service
from Products.PlonePAS.tools.memberdata import MemberData as MemberData

DEFAULT_SEARCH_RESULTS_LIMIT: int

def getPortraitUrl(user): ...
def isDefaultPortrait(value): ...

class UsersGet(Service):
    params: Incomplete
    portal_membership: Incomplete
    acl_users: Incomplete
    query: Incomplete
    search_term: Incomplete
    def __init__(self, context, request) -> None: ...
    def publishTraverse(self, request, name): ...
    def has_permission_to_query(self): ...
    def has_permission_to_enumerate(self): ...
    def has_permission_to_access_user_info(self): ...
    def reply(self): ...

class PortraitGet(Service):
    allowed_inline_mimetypes = ALLOWED_INLINE_MIMETYPES
    disallowed_inline_mimetypes = DISALLOWED_INLINE_MIMETYPES
    use_denylist = USE_DENYLIST
    params: Incomplete
    portal: Incomplete
    portal_membership: Incomplete
    def __init__(self, context, request) -> None: ...
    def publishTraverse(self, request, name): ...
    def render(self): ...
