from _typeshed import Incomplete
from plone.restapi.services import Service

class UsersPatch(Service):
    """Updates an existing user."""

    params: Incomplete
    def __init__(self, context, request) -> None: ...
    @property
    def is_zope_manager(self): ...
    def can_change_roles(self, target_roles, current_roles): ...
    def can_change(self, current_roles): ...
    def publishTraverse(self, request, name): ...
    def translate(self, msgid): ...
    def reply(self): ...
    @property
    def can_manage_users(self): ...
    @property
    def can_set_own_password(self): ...
    def set_member_portrait(self, user, portrait) -> None: ...
