from _typeshed import Incomplete
from plone.app.contentlisting.contentlisting import BaseContentListingObject

missing: Incomplete

class CatalogContentListingObject(BaseContentListingObject):
    """A Catalog-results based content object representation.

    Whenever sequences of catalog brains are turned into contentlistings,
    This is the type of objects they are adapted to.
    """

    request: Incomplete
    def __init__(self, brain) -> None: ...
    def __getattr__(self, name):
        """We'll override getattr so that we can defer name lookups to the real
        underlying objects without knowing the names of all attributes.
        """
    def getDataOrigin(self): ...
    def getObject(self): ...
    def getId(self): ...
    def getPath(self): ...
    def getURL(self, relative: bool = False): ...
    def uuid(self): ...
    def getSize(self): ...
    def review_state(self): ...
    def Title(self): ...
    def Description(self): ...
    def CroppedDescription(self): ...
    def Type(self): ...
    def PortalType(self): ...
    def listCreators(self): ...
    def getUserData(self, username): ...
    def Creator(self): ...
    def Author(self): ...
    def Subject(self): ...
    def Publisher(self) -> None: ...
    def listContributors(self) -> None: ...
    def Contributors(self): ...
    def Date(self, zone=None): ...
    def CreationDate(self, zone=None): ...
    def EffectiveDate(self, zone=None): ...
    def ExpirationDate(self, zone=None): ...
    def ModificationDate(self, zone=None): ...
    def Format(self) -> None: ...
    def Identifier(self): ...
    def Language(self): ...
    def Rights(self) -> None: ...
