from _typeshed import Incomplete
from plone.app.contentlisting.contentlisting import BaseContentListingObject

MARKER: Incomplete

class RealContentListingObject(BaseContentListingObject):
    """A content object representation wrapping a real content object."""

    request: Incomplete
    def __init__(self, obj) -> None: ...
    def __getattr__(self, name):
        """We'll override getattr so that we can defer name lookups to
        the real underlying objects without knowing the names of all
        attributes.
        """
    def getObject(self): ...
    def getDataOrigin(self): ...
    def getPath(self): ...
    def getURL(self): ...
    def uuid(self): ...
    def getSize(self): ...
    def review_state(self): ...
    def Type(self): ...
    def PortalType(self): ...
    def image_scales(self): ...
