from _typeshed import Incomplete

ANNOTATION_KEY: str

class TTWLockable:
    """An object that is being locked through-the-web"""

    context: Incomplete
    def __init__(self, context) -> None: ...
    def lock(self, lock_type=..., children: bool = False) -> None: ...
    def refresh_lock(self, lock_type=...) -> None: ...
    def unlock(self, lock_type=..., stealable_only: bool = True) -> None: ...
    def clear_locks(self) -> None: ...
    def locked(self): ...
    def can_safely_unlock(self, lock_type=...): ...
    def stealable(self, lock_type=...): ...
    def lock_info(self): ...
