"""Partial stubs for :mod:`zope.interface.common.mapping`."""

from zope.interface import Interface

class IItemMapping(Interface): ...
class IReadMapping(IItemMapping): ...
class IWriteMapping(Interface): ...
class IEnumerableMapping(IReadMapping): ...
class IMapping(IWriteMapping, IEnumerableMapping): ...
class IIterableMapping(IEnumerableMapping): ...
class IClonableMapping(Interface): ...
class IExtendedReadMapping(IIterableMapping): ...
class IExtendedWriteMapping(IWriteMapping): ...
class IFullMapping(IExtendedReadMapping, IExtendedWriteMapping, IMapping): ...
