"""Partial stubs for :mod:`zope.interface.common.sequence`."""

from zope.interface import Interface

class IMinimalSequence(Interface): ...
class IReadSequence(IMinimalSequence): ...
class IFiniteSequence(IReadSequence): ...
class IExtendedReadSequence(IReadSequence): ...
class IUniqueMemberWriteSequence(Interface): ...
class IWriteSequence(IUniqueMemberWriteSequence): ...
class ISequence(IReadSequence, IWriteSequence): ...
