from _typeshed import Incomplete
from plone.memoize.instance import memoize
from zope.publisher.browser import BrowserView

logger: Incomplete

def authorize(context, request) -> None: ...

class ThemingControlpanel(BrowserView):
    @property
    def site_url(self):
        """Return the absolute URL to the current site, which is likely not
        necessarily the portal root.
        """
    @property
    def hostname_blacklist(self): ...
    pskin: Incomplete
    def __call__(self): ...
    def redirect(self, url) -> None: ...
    def get_mark_special_links(self): ...
    def set_mark_special_links(self, value) -> None: ...
    mark_special_links: Incomplete
    def get_ext_links_open_new_window(self): ...
    def set_ext_links_open_new_window(self, value) -> None: ...
    ext_links_open_new_window: Incomplete
    errors: Incomplete
    def update(self): ...
    def getSelectedTheme(self, themes, themeName, rules): ...
    def getThemeData(self, themes, themeSelection): ...
    @memoize
    def themeList(self): ...
    def redirectToFieldset(self, fieldset) -> None: ...
    overlay: Incomplete
    def renderOverlay(self, overlay) -> None: ...
    def authorize(self): ...
