from plone.restapi.controlpanels import RegistryConfigletPanel

class ContentRulesControlpanel(RegistryConfigletPanel):
    configlet_id: str
    configlet_category_id: str
    def publishTraverse(self, request, name): ...
    def add(self, names): ...
    def get(self, names): ...
    def update(self, names): ...
    def delete(self, names): ...
