from plone.restapi.controlpanels import RegistryConfigletPanel

class DexterityTypesControlpanel(RegistryConfigletPanel):
    configlet_id: str
    configlet_category_id: str
    def add(self, names): ...
    def get(self, names): ...
    def update(self, names): ...
    def delete(self, names) -> None: ...
