from plone.restapi.deserializer.controlpanels import ControlpanelDeserializeFromJson

class DexterityTypesControlpanelDeserializeFromJson(ControlpanelDeserializeFromJson):
    def deserialize_item(self, proxy) -> None: ...
    def __call__(self, item=None): ...
