from Products.Five.browser import BrowserView

class ObjectManagerSiteView(BrowserView):
    def update(self) -> None: ...
    def isSite(self): ...
    def makeSite(self) -> None: ...
    def unmakeSite(self) -> None: ...
