from _typeshed import Incomplete

MIGRATION: Incomplete

def migrate_content_classes(context) -> None:
    """Migrate content created with collective.folderishtypes to plone.volto."""

def from12to13_migrate_listings(context): ...
def remove_plone_richtext_behavior(context) -> None: ...
def add_control_panel_classic_icon(context) -> None: ...
def add_block_types_index(context) -> None: ...
def rename_distribution(context) -> None: ...

ROBOTS_TXT: str

def update_robots_txt(context) -> None: ...
