def objectAdded(ev) -> None: ...
def objectModified(ev) -> None: ...
def objectCopied(ev) -> None: ...
def objectRemoved(ev) -> None: ...
def objectMoved(ev) -> None: ...
def dispatchObjectMovedEvent(ob, ev) -> None:
    """dispatch events to sub-items when a folderish item has been renamed"""

def objectTransitioned(ev) -> None: ...
