from _typeshed import Incomplete

def exportPAS(context) -> None: ...
def importPAS(context) -> None: ...

class PAS_PR_ContentFactory:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def __call__(self, object_id): ...

class PAS_CF_Namer:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def __call__(self): ...
