from _typeshed import Incomplete

logger: Incomplete

def log(message, summary: str = "", severity=...) -> None: ...
def log_exc(message: str = "", summary: str = "", severity=...) -> None: ...
def log_deprecated(
    message, summary: str = "Deprecation Warning", severity=...
) -> None: ...
