from _typeshed import Incomplete
from Products.CMFCore.utils import ToolInit as CMFCoreToolInit
from Products.CMFPlone.log import log_deprecated as log_deprecated
from Products.CMFPlone.log import log_exc as log_exc
from zope.deprecation import deprecated as deprecated

ClassType = type

def safe_encode(*args, **kwargs): ...
def safe_unicode(*args, **kwargs): ...
def safe_nativestring(value, encoding: str = "utf-8"):
    """Convert a value to str in py2 and to text in py3"""

security: Incomplete
PACKAGE_HOME: Incomplete
WWW_DIR: Incomplete
QUALITY_DEFAULT: int
pattern: Incomplete

def get_portal():
    """get the Plone portal object.

    It fetched w/o any further context by using the last registered site.
    So this work only after traversal time.
    """

def parent(obj): ...
def createBreadCrumbs(context, request): ...
def createSiteMap(context, request, sitemap: bool = False): ...
def isExpired(content):
    """Find out if the object is expired (copied from skin script)"""

def typesToList(context): ...
def normalizeString(text, context=None, encoding=None): ...

class RealIndexIterator:
    """The 'real' version of the IndexIterator class, that's actually
    used to generate unique indexes.
    """

    __allow_access_to_unprotected_subobjects__: int
    pos: Incomplete
    def __init__(self, pos: int = 0) -> None: ...
    def __next__(self): ...
    next = __next__

class ToolInit(CMFCoreToolInit):
    def getProductContext(self, context): ...
    def getPack(self, context): ...
    def getIcon(self, context, path): ...
    def initialize(self, context) -> None: ...

release_levels: Incomplete
rl_abbr: Incomplete

def versionTupleFromString(v_str):
    """Returns version tuple from passed in version string

    >>> versionTupleFromString('1.2.3')
    (1, 2, 3, 'final', 0)

    >>> versionTupleFromString('2.1-final1 (SVN)')
    (2, 1, 0, 'final', 1)

    >>> versionTupleFromString('3-beta')
    (3, 0, 0, 'beta', 0)

    >>> versionTupleFromString('2.0a3')
    (2, 0, 0, 'alpha', 3)

    >>> versionTupleFromString('foo') is None
    True
    """

def getFSVersionTuple():
    """Returns Products.CMFPlone version tuple"""

def transaction_note(note) -> None:
    """Write human legible note"""

def tuplize(value): ...
def flatten(interfaces): ...
def directlyProvides(obj, *interfaces): ...
def classImplements(class_, *interfaces): ...
def classDoesNotImplement(class_, *interfaces): ...
def webdav_enabled(obj, container):
    """WebDAV check used in externalEditorEnabled.py"""

def set_own_login_name(member, loginname) -> None:
    """Allow the user to set his/her own login name.

    If you have the Manage Users permission, you can update the login
    name of another member too, though the name of this function is a
    bit weird then.  Historical accident.
    """

def ajax_load_url(url): ...
def bodyfinder(text):
    """Return body or unchanged text if no body tags found.

    Always use html_headcheck() first.
    """

def getSiteLogo(site=None, include_type: bool = False): ...
def check_id(
    context,
    id=None,
    required: int = 0,
    alternative_id=None,
    contained_by=None,
    **kwargs,
):
    """Test an id to make sure it is valid.

    This used to be in Products/CMFPlone/skins/plone_scripts/check_id.py.

    Returns an error message if the id is bad or None if the id is good.
    Parameters are as follows:

        id - the id to check

        required - if False, id can be the empty string

        alternative_id - an alternative value to use for the id
        if the id is empty or autogenerated

    Accept keyword arguments for compatibility with the fallback
    in Products.validation.

    Note: The reason the id is included is to handle id error messages for
    such objects as files and images that supply an alternative id when an
    id is auto-generated.
    If you say "There is already an item with this name in this folder"
    for an image that has the Name field populated with an autogenerated id,
    it can cause some confusion; since the real problem is the name of
    the image file name, not in the name of the autogenerated id.
    """
