from _typeshed import Incomplete
from Products.CMFCore.WorkflowTool import WorkflowTool as BaseTool
from Products.CMFPlone.PloneBaseTool import PloneBaseTool

multilingual_version: Incomplete
has_new_lang_bypass: bool

class WorkflowTool(PloneBaseTool, BaseTool):
    meta_type: str
    security: Incomplete
    plone_tool: int
    toolicon: str
    def flattenTransitions(self, objs, container=None): ...
    def flattenTransitionsForPaths(self, paths): ...
    def getTransitionsFor(self, obj=None, container=None, REQUEST=None): ...
    def workflows_in_use(self): ...
    def getWorklists(self): ...
    def getWorklistsResults(self): ...
    def getChainForPortalType(self, pt_name, managescreen: int = 0): ...
    def listWorkflows(self): ...
    def getTitleForStateOnType(self, state_name, p_type): ...
    def getTitleForTransitionOnType(self, trans_name, p_type): ...
    def listWFStatesByTitle(self, filter_similar: bool = False): ...
    def getChainFor(self, ob): ...
    def listActions(self, info=None, object=None):
        """Returns a list of actions to be displayed to the user.

        o Invoked by the portal_actions tool.

        o Allows workflows to include actions to be displayed in the
          actions box.

        o Object actions are supplied by workflows that apply to the object.
        """
