from _typeshed import Incomplete
from Persistence import Persistent

LOG: Incomplete

class FilteredSetBase(Persistent):
    id: Incomplete
    expr: Incomplete
    def __init__(self, id, expr) -> None: ...
    ids: Incomplete
    def clear(self) -> None: ...
    def index_object(self, documentId, obj) -> None: ...
    def unindex_object(self, documentId) -> None: ...
    def getId(self): ...
    def getExpression(self): ...
    def getIds(self): ...
    def getType(self): ...
    def setExpression(self, expr) -> None: ...

class PythonFilteredSet(FilteredSetBase):
    meta_type: str
    def index_object(self, documentId, o) -> None: ...

def factory(f_id, f_type, expr):
    """factory function for FilteredSets"""
