from _typeshed import Incomplete
from collections.abc import Generator
from zope.cachedescriptors.property import Lazy as lazy_property

class BaseFeedData:
    context: Incomplete
    settings: Incomplete
    site: Incomplete
    pm: Incomplete
    view_action_types: Incomplete
    def __init__(self, context) -> None: ...
    @lazy_property
    def show_about(self): ...
    @property
    def link(self): ...
    @lazy_property
    def base_url(self): ...
    @lazy_property
    def canonical_url(self): ...
    @property
    def title(self): ...
    @property
    def description(self): ...
    @property
    def categories(self): ...
    @property
    def published(self): ...
    @property
    def modified(self): ...
    @property
    def uid(self): ...
    @property
    def rights(self): ...
    @property
    def publisher(self): ...

class FolderFeed(BaseFeedData):
    @lazy_property
    def author(self): ...
    @property
    def author_name(self): ...
    @property
    def author_email(self): ...
    @property
    def logo(self): ...
    @property
    def icon(self): ...
    @property
    def items(self) -> Generator[Incomplete]: ...
    @property
    def limit(self): ...
    @property
    def language(self): ...

class CollectionFeed(FolderFeed): ...
class SearchFeed(FolderFeed): ...

class BaseItem(BaseFeedData):
    context: Incomplete
    feed: Incomplete
    def __init__(self, context, feed) -> None: ...
    @lazy_property
    def creator(self): ...
    @lazy_property
    def author(self): ...
    @property
    def author_name(self): ...
    @property
    def author_email(self): ...
    @property
    def body(self): ...
    content_core_template: Incomplete
    request: Incomplete
    def render_content_core(self): ...
    @property
    def link(self): ...
    guid = link
    @property
    def has_enclosure(self): ...
    @lazy_property
    def file(self): ...
    @property
    def file_url(self): ...
    @property
    def file_length(self): ...
    @property
    def file_type(self): ...

class DexterityItem(BaseItem):
    file: Incomplete
    field_name: str
    dexterity: Incomplete
    def __init__(self, context, feed) -> None: ...
    @property
    def file_url(self): ...
    @property
    def has_enclosure(self): ...
    @property
    def file_length(self): ...
    @property
    def file_type(self): ...
