from plone.memoize.view import memoize
from Products.Five import BrowserView

class SyndicationUtil(BrowserView):
    def allowed_feed_types(self): ...
    def rss_url(self): ...
    def context_allowed(self): ...
    def context_enabled(self, raise404: bool = False): ...
    @property
    @memoize
    def site_settings(self): ...
    def site_enabled(self): ...
    def search_rss_enabled(self, raise404: bool = False): ...
    def show_author_info(self): ...
    def max_items(self): ...
