from _typeshed import Incomplete

LOG: Incomplete

class StdoutHandler:
    """A simple progress handler"""
    def __init__(self, steps: int = 100) -> None: ...
    savepoint: Incomplete
    fp: Incomplete
    def init(self, ident, max, savepoint: bool = True) -> None: ...
    def info(self, text) -> None: ...
    def finish(self) -> None: ...
    def report(self, current, *args, **kw) -> None: ...
    def output(self, text) -> None: ...

class ZLogHandler(StdoutHandler):
    """Use Zope logger"""
    def output(self, text) -> None: ...

class FilelogHandler(StdoutHandler):
    """Use a custom file for logging"""

    filename: Incomplete
    def __init__(self, filename, steps: int = 100) -> None: ...
    def output(self, text) -> None: ...
