from _typeshed import Incomplete
from collections.abc import Generator
from plone.restapi.services import Service

class ControlpanelsUpdate(Service):
    params: Incomplete
    def __init__(self, context, request) -> None: ...
    def publishTraverse(self, request, name): ...
    def get_controlpanel_adapters(self) -> Generator[Incomplete]: ...
    def panel_by_name(self, name): ...
    def reply(self): ...
