from _typeshed import Incomplete
from Products.Five.browser import BrowserView
from z3c.form import form
from zope.interface import Interface

class LockingBase(BrowserView):
    @property
    def is_locked(self): ...

class DeleteConfirmationForm(form.Form, LockingBase):
    fields: Incomplete
    template: Incomplete
    enableCSRFProtection: bool
    def view_url(self):
        """Facade to the homonymous plone_context_state method"""
    def more_info(self): ...
    @property
    def items_to_delete(self): ...
    def handle_delete(self, action) -> None: ...
    def handle_cancel(self, action): ...
    def updateActions(self) -> None: ...

def valid_id(self): ...

class IRenameForm(Interface):
    new_id: Incomplete
    new_title: Incomplete

default_new_id: Incomplete
default_new_title: Incomplete

class RenameForm(form.Form):
    fields: Incomplete
    template: Incomplete
    enableCSRFProtection: bool
    ignoreContext: bool
    label: Incomplete
    description: Incomplete
    def view_url(self): ...
    def handle_rename(self, action) -> None: ...
    def handle_cancel(self, action) -> None: ...
    def updateActions(self) -> None: ...

class ObjectCutView(BrowserView):
    @property
    def title(self): ...
    @property
    def parent(self): ...
    @property
    def canonical_object_url(self): ...
    @property
    def view_url(self): ...
    def do_redirect(
        self, url, message=None, message_type: str = "info", raise_exception=None
    ): ...
    def do_action(self): ...
    def __call__(self): ...

class ObjectCopyView(ObjectCutView):
    def do_action(self): ...

class ObjectDeleteView(ObjectCutView):
    def do_action(self) -> None: ...

class ObjectPasteView(ObjectCutView):
    def do_action(self): ...
