from _typeshed import Incomplete
from plone.app.content.browser.tableview import TableBrowserView
from zope.publisher.browser import BrowserView

class FullReviewListView(BrowserView):
    def revlist(self): ...
    def url(self): ...
    def review_table(self): ...

class ReviewListTable:
    """
    The review list table renders the table and its actions.
    """

    context: Incomplete
    request: Incomplete
    table: Incomplete
    def __init__(self, context, request, **kwargs) -> None: ...
    def render(self): ...
    @property
    def items(self): ...
    @property
    def show_sort_column(self): ...
    def buttons(self): ...
    def setbuttonclass(self, button): ...

class ReviewListBrowserView(TableBrowserView):
    table = ReviewListTable
