from _typeshed import Incomplete
from Products.Five.browser import BrowserView

class DefaultViewSelectionView(BrowserView):
    def isValidTemplate(self, templateId): ...
    def canSelectDefaultPage(self): ...
    @property
    def vocab(self): ...
    @property
    def selectedLayout(self): ...
    def selectViewTemplate(self) -> None: ...
    @property
    def action_url(self): ...
    context_state: Incomplete
    def __call__(self): ...

class DefaultPageSelectionView(BrowserView):
    def __call__(self): ...
    def get_selectable_items(self):
        """Return brains in this container that can be used as default_pages"""
