from _typeshed import Incomplete

class DefaultLanguageIndependentFieldsManager:
    """Default language independent fields manager."""

    context: Incomplete
    def __init__(self, context) -> None: ...
    def get_field_names(self): ...
    def copy_fields(self, translation) -> None: ...

class DefaultTranslationLocator:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def __call__(self, language):
        """
        Look for the closest translated folder or siteroot
        """

class DefaultTranslationCloner:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def __call__(self, obj) -> None: ...

class DefaultTranslationIdChooser:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def __call__(self, parent, language): ...

class DefaultTranslationFactory:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def __call__(self, language): ...
