from _typeshed import Incomplete

def attributeTG(context): ...

class MutableAttributeTG:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def get(self): ...
    def set(self, tg) -> None: ...

def addAttributeTG(obj, event) -> None: ...
