import ExtensionClass
import zope.pagetemplate.pagetemplate

class PageTemplate(ExtensionClass.Base, zope.pagetemplate.pagetemplate.PageTemplate):
    def pt_getEngine(self): ...
    def pt_getContext(self): ...
    @property
    def macros(self): ...
    def pt_macros(self): ...
    def pt_render(self, source: bool = False, extra_context={}): ...
    def pt_errors(self, namespace={}, check_macro_expansion=None): ...
    def __call__(self, *args, **kwargs): ...
    def read(self): ...
    def html(self): ...
