from _typeshed import Incomplete
from plone.app.layout.viewlets import ViewletBase
from plone.memoize.instance import memoize
from plone.memoize.view import memoize_contextless
from Products.Five.browser import BrowserView

class DocumentActionsViewlet(ViewletBase):
    index: Incomplete
    context_state: Incomplete
    actions: Incomplete
    def update(self) -> None: ...

class DocumentBylineViewlet(ViewletBase):
    index: Incomplete
    anonymous: Incomplete
    def update(self) -> None: ...
    @property
    def context_state(self): ...
    @property
    def has_pam(self): ...
    @property
    @memoize_contextless
    def portal_membership(self): ...
    def show(self): ...
    def show_about(self): ...
    def creator(self): ...
    def author(self): ...
    def authorname(self): ...
    @memoize
    def get_member_info(self, user_id): ...
    def get_url_path(self, user_id): ...
    def get_fullname(self, user_id): ...
    def show_modification_date(self): ...
    def isExpired(self): ...
    def toLocalizedTime(self, time, long_format=None, time_only=None):
        """Convert time to localized time"""
    def pub_date(self):
        """Return object effective date.

        Return None if publication date is switched off in global site settings
        or if Effective Date is not set on object.
        """
    def get_translations(self): ...

class HistoryByLineView(BrowserView):
    """DocumentByLine information for content history view"""

    index: Incomplete
    portal_state: Incomplete
    context_state: Incomplete
    anonymous: Incomplete
    def update(self) -> None: ...
    def __call__(self): ...
    @property
    def has_pam(self): ...
    def show(self): ...
    def show_history(self): ...
    def locked_icon(self): ...
    def creator(self): ...
    def author(self): ...
    def authorname(self): ...
    def isExpired(self): ...
    def toLocalizedTime(self, time, long_format=None, time_only=None):
        """Convert time to localized time"""
    def pub_date(self):
        """Return object effective date.

        Return None if publication date is switched off in global site settings
        or if Effective Date is not set on object.
        """
    def get_translations(self): ...

class ContentRelatedItems(ViewletBase):
    index: Incomplete
    def related_items(self): ...
    def related2brains(self, related):
        """Return a list of brains based on a list of relations. Will filter
        relations if the user has no permission to access the content.

        :param related: related items
        :type related: list of relations
        :return: list of catalog brains
        """

class WorkflowHistoryViewlet(ViewletBase):
    index: Incomplete
    @memoize
    def getUserInfo(self, userid): ...
    def workflowHistory(self, complete: bool = True):
        """Return workflow history of this context.

        Taken from plone_scripts/getWorkflowHistory.py
        """

class ContentHistoryViewlet(WorkflowHistoryViewlet):
    index: Incomplete
    def revisionHistory(self): ...
    def fullHistory(self): ...
    def toLocalizedTime(self, time, long_format=None, time_only=None):
        """Convert time to localized time"""

class ContentHistoryView(ContentHistoryViewlet):
    def __init__(self, context, request) -> None: ...
    def __call__(self): ...
