from _typeshed import Incomplete
from plone.app.viewletmanager.manager import OrderedViewletManager
from plone.memoize.instance import memoize

class ToolbarViewletManager(OrderedViewletManager):
    custom_template: Incomplete
    def base_render(self): ...
    def render(self): ...
    @property
    @memoize
    def context_state(self): ...
    @property
    @memoize
    def portal_state(self): ...
    def toolbar_position(self): ...
    def get_personal_bar(self): ...
    def get_toolbar_logo(self): ...
    def show_switcher(self): ...
