"""Partial stubs for :mod:`zope.component`.

The ZCA lookup helpers are typed generically so that, e.g.,
``getUtility(IFoo)`` is inferred to return ``IFoo``. This replaces the type
information the ``mypy-zope`` plugin used to synthesise, and works across all
PEP 561 checkers.
"""

from collections.abc import Callable
from collections.abc import Iterator
from typing import Any
from typing import TypeVar
from zope.component.interfaces import IComponentLookup

_T = TypeVar("_T")
_C = TypeVar("_C", bound=type)

def getGlobalSiteManager() -> IComponentLookup: ...
def getSiteManager(context: Any = ...) -> IComponentLookup: ...
def getUtility(interface: type[_T], name: str = ..., context: Any = ...) -> _T: ...
def queryUtility(
    interface: type[_T], name: str = ..., default: _T | None = ..., context: Any = ...
) -> _T | None: ...
def getAdapter(
    object: Any, interface: type[_T], name: str = ..., context: Any = ...
) -> _T: ...
def queryAdapter(
    object: Any,
    interface: type[_T],
    name: str = ...,
    default: _T | None = ...,
    context: Any = ...,
) -> _T | None: ...
def getMultiAdapter(
    objects: tuple[Any, ...], interface: type[_T], name: str = ..., context: Any = ...
) -> _T: ...
def queryMultiAdapter(
    objects: tuple[Any, ...],
    interface: type[_T],
    name: str = ...,
    default: _T | None = ...,
    context: Any = ...,
) -> _T | None: ...
def getUtilitiesFor(
    interface: type[_T], context: Any = ...
) -> Iterator[tuple[str, _T]]: ...
def getAllUtilitiesRegisteredFor(
    interface: type[_T], context: Any = ...
) -> Iterator[_T]: ...
def getAdapters(
    objects: tuple[Any, ...], provided: type[_T], context: Any = ...
) -> Iterator[tuple[str, _T]]: ...
def subscribers(
    objects: tuple[Any, ...], interface: type[_T], context: Any = ...
) -> list[_T]: ...
def handle(*objects: Any) -> None: ...
def createObject(name: str, *args: Any, context: Any = ..., **kwargs: Any) -> Any: ...
def adapter(*interfaces: Any) -> Callable[[_C], _C]: ...
def provideUtility(component: Any, provides: Any = ..., name: str = ...) -> None: ...
def provideAdapter(
    factory: Any, adapts: Any = ..., provides: Any = ..., name: str = ...
) -> None: ...
def provideSubscriptionAdapter(
    factory: Any, adapts: Any = ..., provides: Any = ...
) -> None: ...
def provideHandler(factory: Any, adapts: Any = ...) -> None: ...
