"""Partial stubs for :mod:`zope.component`.

The ZCA lookup helpers are typed generically so that, e.g.,
``getUtility(IFoo)`` is inferred to return ``IFoo``. This replaces the type
information the ``mypy-zope`` plugin used to synthesise, and works across all
PEP 561 checkers.
"""

from collections.abc import Callable
from collections.abc import Iterator
from typing import Any
from zope.component.interfaces import IComponentLookup

def getGlobalSiteManager() -> IComponentLookup: ...
def getSiteManager(context: Any = ...) -> IComponentLookup: ...
def getUtility[T](interface: type[T], name: str = ..., context: Any = ...) -> T: ...
def queryUtility[T](
    interface: type[T], name: str = ..., default: T | None = ..., context: Any = ...
) -> T | None: ...
def getAdapter[T](
    object: Any, interface: type[T], name: str = ..., context: Any = ...
) -> T: ...
def queryAdapter[T](
    object: Any,
    interface: type[T],
    name: str = ...,
    default: T | None = ...,
    context: Any = ...,
) -> T | None: ...
def getMultiAdapter[T](
    objects: tuple[Any, ...], interface: type[T], name: str = ..., context: Any = ...
) -> T: ...
def queryMultiAdapter[T](
    objects: tuple[Any, ...],
    interface: type[T],
    name: str = ...,
    default: T | None = ...,
    context: Any = ...,
) -> T | None: ...
def getUtilitiesFor[T](
    interface: type[T], context: Any = ...
) -> Iterator[tuple[str, T]]: ...
def getAllUtilitiesRegisteredFor[T](
    interface: type[T], context: Any = ...
) -> Iterator[T]: ...
def getAdapters[T](
    objects: tuple[Any, ...], provided: type[T], context: Any = ...
) -> Iterator[tuple[str, T]]: ...
def subscribers[T](
    objects: tuple[Any, ...], interface: type[T], context: Any = ...
) -> list[T]: ...
def handle(*objects: Any) -> None: ...
def createObject(name: str, *args: Any, context: Any = ..., **kwargs: Any) -> Any: ...
def adapter[C: type](*interfaces: Any) -> Callable[[C], C]: ...
def provideUtility(component: Any, provides: Any = ..., name: str = ...) -> None: ...
def provideAdapter(
    factory: Any, adapts: Any = ..., provides: Any = ..., name: str = ...
) -> None: ...
def provideSubscriptionAdapter(
    factory: Any, adapts: Any = ..., provides: Any = ...
) -> None: ...
def provideHandler(factory: Any, adapts: Any = ...) -> None: ...
