"""Partial stubs for :mod:`zope.component.hooks`."""

from contextlib import AbstractContextManager
from OFS.SimpleItem import SimpleItem
from zope.component.interfaces import IComponentLookup
from zope.component.interfaces import ISite

def setSite(site: ISite = ...) -> None: ...
def getSite() -> ISite: ...
def getSiteManager(context: SimpleItem = ...) -> IComponentLookup: ...
def setHooks() -> None: ...
def resetHooks() -> None: ...
def clearSite() -> None: ...
def site(site: ISite) -> AbstractContextManager[ISite]: ...
