"""Partial stubs for :mod:`zope.component.interfaces`.

Signatures mirror the runtime interfaces. Lookup methods that take an
interface and return a provider are typed generically so that, e.g.,
``getSiteManager().getUtility(IFoo)`` is inferred as ``IFoo``.
"""

from collections.abc import Iterator
from typing import Any
from zope.interface import Interface

class IComponentLookup(Interface):
    """A component registry — the object returned by ``getSiteManager()``."""

    adapters: Any
    utilities: Any

    def queryAdapter[T](
        self, object: Any, interface: type[T], name: str = ..., default: Any = ...
    ) -> T | None: ...
    def getAdapter[T](self, object: Any, interface: type[T], name: str = ...) -> T: ...
    def queryMultiAdapter[T](
        self,
        objects: tuple[Any, ...],
        interface: type[T],
        name: str = ...,
        default: Any = ...,
    ) -> T | None: ...
    def getMultiAdapter[T](
        self, objects: tuple[Any, ...], interface: type[T], name: str = ...
    ) -> T: ...
    def getAdapters(
        self, objects: tuple[Any, ...], provided: Any
    ) -> Iterator[tuple[str, Any]]: ...
    def subscribers(self, objects: tuple[Any, ...], provided: Any) -> list[Any]: ...
    def handle(self, *objects: Any) -> None: ...
    def queryUtility[T](
        self, interface: type[T], name: str = ..., default: Any = ...
    ) -> T | None: ...
    def getUtilitiesFor[T](self, interface: type[T]) -> Iterator[tuple[str, T]]: ...
    def getAllUtilitiesRegisteredFor[T](self, interface: type[T]) -> Iterator[T]: ...

class IComponentRegistry(Interface):
    def registerUtility(
        self,
        component: Any = ...,
        provided: Any = ...,
        name: str = ...,
        info: str = ...,
        factory: Any = ...,
    ) -> None: ...
    def unregisterUtility(
        self,
        component: Any = ...,
        provided: Any = ...,
        name: str = ...,
        factory: Any = ...,
    ) -> bool: ...
    def registerAdapter(
        self,
        factory: Any,
        required: Any = ...,
        provided: Any = ...,
        name: str = ...,
        info: str = ...,
    ) -> None: ...
    def unregisterAdapter(
        self,
        factory: Any = ...,
        required: Any = ...,
        provided: Any = ...,
        name: str = ...,
    ) -> bool: ...
    def registerHandler(
        self, handler: Any, required: Any = ..., info: str = ...
    ) -> None: ...
    def unregisterHandler(self, handler: Any = ..., required: Any = ...) -> bool: ...

class IComponents(IComponentLookup, IComponentRegistry):
    """A registry providing both lookup and registration."""

class IComponentArchitecture(Interface):
    """Documents the ``zope.component`` API surface."""

    def getGlobalSiteManager(self) -> IComponentLookup: ...
    def getSiteManager(self, context: Any = ...) -> IComponentLookup: ...
    def getUtility[T](
        self, interface: type[T], name: str = ..., context: Any = ...
    ) -> T: ...
    def queryUtility[T](
        self,
        interface: type[T],
        name: str = ...,
        default: Any = ...,
        context: Any = ...,
    ) -> T | None: ...
    def queryNextUtility[T](
        self, context: Any, interface: type[T], name: str = ..., default: Any = ...
    ) -> T | None: ...
    def getNextUtility[T](
        self, context: Any, interface: type[T], name: str = ...
    ) -> T: ...
    def getUtilitiesFor[T](
        self, interface: type[T], context: Any = ...
    ) -> Iterator[tuple[str, T]]: ...
    def getAllUtilitiesRegisteredFor[T](
        self, interface: type[T], context: Any = ...
    ) -> Iterator[T]: ...
    def getAdapter[T](
        self, object: Any, interface: type[T], name: str = ..., context: Any = ...
    ) -> T: ...
    def getAdapterInContext[T](
        self, object: Any, interface: type[T], context: Any
    ) -> T: ...
    def getMultiAdapter[T](
        self,
        objects: tuple[Any, ...],
        interface: type[T],
        name: str = ...,
        context: Any = ...,
    ) -> T: ...
    def queryAdapter[T](
        self,
        object: Any,
        interface: type[T] = ...,
        name: str = ...,
        default: Any = ...,
        context: Any = ...,
    ) -> T | None: ...
    def queryAdapterInContext[T](
        self, object: Any, interface: type[T], context: Any, default: Any = ...
    ) -> T | None: ...
    def queryMultiAdapter[T](
        self,
        objects: tuple[Any, ...],
        interface: type[T],
        name: str = ...,
        default: Any = ...,
        context: Any = ...,
    ) -> T | None: ...
    def getAdapters(
        self, objects: tuple[Any, ...], provided: Any, context: Any = ...
    ) -> Iterator[tuple[str, Any]]: ...
    def subscribers(
        self, required: tuple[Any, ...], provided: Any, context: Any = ...
    ) -> list[Any]: ...
    def handle(self, *objects: Any) -> None: ...
    def adapts(self, *interfaces: Any) -> None: ...
    def createObject(self, factory_name: str, *args: Any, **kwargs: Any) -> Any: ...
    def getFactoryInterfaces(self, name: str, context: Any = ...) -> Any: ...
    def getFactoriesFor(self, interface: Any, context: Any = ...) -> Any: ...

class IRegistry(Interface):
    def registrations(self) -> Iterator[Any]: ...

class IComponentRegistrationConvenience(Interface):
    def provideUtility(
        self, component: Any, provides: Any = ..., name: str = ...
    ) -> None: ...
    def provideAdapter(
        self, factory: Any, adapts: Any = ..., provides: Any = ..., name: str = ...
    ) -> None: ...
    def provideSubscriptionAdapter(
        self, factory: Any, adapts: Any = ..., provides: Any = ...
    ) -> None: ...
    def provideHandler(self, handler: Any, adapts: Any = ...) -> None: ...

class IPossibleSite(Interface):
    def setSiteManager(self, sitemanager: IComponentLookup) -> None: ...
    def getSiteManager(self) -> IComponentLookup: ...

class ISite(IPossibleSite):
    """A site that holds a local component registry."""

class IFactory(Interface):
    title: str
    description: str

    def __call__(self, *args: Any, **kw: Any) -> Any: ...
    def getInterfaces(self) -> Any: ...

class IObjectEvent(Interface):
    object: Any

class IRegistered(IObjectEvent): ...
class IUnregistered(IObjectEvent): ...
class Invalid(Exception): ...
class ComponentLookupError(Exception): ...
class Misused(Exception): ...
