from _typeshed import Incomplete

isProxyOrReference: Incomplete

def getNonVersionedDataAdapter(obj):
    """Returns an INonVersionedData adapter for any object.

    This is a super-simplistic adapter implementation.
    """

def listNonVersionedObjects(obj): ...
def getNonVersionedData(obj): ...
def removeNonVersionedData(obj) -> None: ...
def restoreNonVersionedData(obj, dict) -> None: ...

class StandardNonVersionedDataAdapter:
    """Non-versioned data adapter for arbitrary things."""

    obj: Incomplete
    attrs: Incomplete
    def __init__(self, obj) -> None: ...
    def listNonVersionedObjects(self): ...
    def removeNonVersionedData(self) -> None: ...
    def getNonVersionedData(self): ...
    def restoreNonVersionedData(self, data) -> None: ...

class ObjectManagerNonVersionedDataAdapter(StandardNonVersionedDataAdapter):
    """Non-versioned data adapter for object managers."""
    def listNonVersionedObjects(self): ...
    def removeNonVersionedData(self) -> None: ...
    def getNonVersionedData(self): ...
    def restoreNonVersionedData(self, data) -> None: ...
