from _typeshed import Incomplete
from Acquisition import Implicit
from Persistence import Persistent

class Repository(Implicit, Persistent):
    """The repository implementation manages the actual data of versions
    and version histories. It does not handle user interface issues."""
    def __init__(self) -> None: ...
    security: Incomplete
    @security.private
    def createVersionHistory(self, object):
        """Internal: create a new version history for a resource."""
    @security.private
    def getVersionHistory(self, history_id):
        """Internal: return a version history given a version history id."""
    @security.private
    def replaceState(self, obj, new_state):
        """Internal: replace the state of a persistent object."""
    @security.public
    def isAVersionableResource(self, obj): ...
    @security.public
    def isUnderVersionControl(self, object): ...
    @security.public
    def isResourceUpToDate(self, object, require_branch: int = 0): ...
    @security.public
    def isResourceChanged(self, object): ...
    @security.public
    def getVersionInfo(self, object): ...
    def applyVersionControl(self, object, message=None): ...
    def checkoutResource(self, object): ...
    def checkinResource(self, object, message: str = ""): ...
    def uncheckoutResource(self, object): ...
    def updateResource(self, object, selector=None): ...
    def labelResource(self, object, label, force: int = 0): ...
    def makeActivity(self, object, branch_id): ...
    def getVersionOfResource(self, history_id, selector): ...
    def getVersionIds(self, object): ...
    def getLabelsForResource(self, object): ...
    def getLogEntries(self, object): ...
