from _typeshed import Incomplete

class SequenceWrapper:
    """A helper that manages lazy acquisition wrapping."""

    pairs: int
    parent: Incomplete
    items: Incomplete
    def __init__(self, parent, items, pairs=None) -> None: ...
    def __getitem__(self, key): ...
    def __len__(self) -> int: ...
    def __nonzero__(self): ...
