from _typeshed import Incomplete
from plone.z3cform import layout
from z3c.form import form

_: Incomplete

class RecordEditForm(form.EditForm):
    """Edit a single record"""

    record: Incomplete
    @property
    def action(self): ...
    def getContent(self): ...
    fields: Incomplete
    def update(self) -> None: ...
    def updateActions(self) -> None: ...
    @property
    def label(self): ...
    status: Incomplete
    def handleSave(self, action) -> None: ...
    def handleCancel(self, action) -> None: ...

class RecordEditView(layout.FormWrapper):
    form = RecordEditForm
    def __init__(self, context, request) -> None: ...
    record: Incomplete
    def publishTraverse(self, request, name): ...
