from _typeshed import Incomplete

logger: Incomplete

def get_desc_for_mimetype(mime_type): ...
def get_ext_for_mimetype(mime_type): ...
def get_mime_types(): ...
def normalize(mt): ...
def initialize() -> None: ...
