from _typeshed import Incomplete

class UTF8Property:
    name: Incomplete
    def __init__(self, name) -> None: ...
    def __get__(self, inst, type=None): ...
    def __set__(self, inst, value) -> None: ...
