from _typeshed import Incomplete
from plone.autoform.form import AutoExtensibleForm
from plone.base.interfaces import IActionSchema
from plone.base.interfaces import INewActionSchema
from Products.Five import BrowserView
from z3c.form import form

class ActionListControlPanel(BrowserView):
    """Control panel for the portal actions."""

    template: Incomplete
    context: Incomplete
    request: Incomplete
    portal_actions: Incomplete
    def __init__(self, context, request) -> None: ...
    actions: Incomplete
    def display(self): ...
    def __call__(self): ...

class ActionControlPanelAdapter:
    """Adapter for action form."""

    context: Incomplete
    current_category: Incomplete
    def __init__(self, context) -> None: ...
    def get_category(self): ...
    def set_category(self, value) -> None: ...
    category: Incomplete
    def get_title(self): ...
    def set_title(self, value) -> None: ...
    title: Incomplete
    def get_description(self): ...
    def set_description(self, value) -> None: ...
    description: Incomplete
    def get_i18n_domain(self): ...
    def set_i18n_domain(self, value) -> None: ...
    i18n_domain: Incomplete
    def get_url_expr(self): ...
    def set_url_expr(self, value) -> None: ...
    url_expr: Incomplete
    def get_available_expr(self): ...
    def set_available_expr(self, value) -> None: ...
    available_expr: Incomplete
    def get_permissions(self): ...
    def set_permissions(self, value) -> None: ...
    permissions: Incomplete
    def get_visible(self): ...
    def set_visible(self, value) -> None: ...
    visible: Incomplete
    def get_position(self): ...
    def set_position(self, value) -> None: ...
    position: Incomplete
    def get_modal(self): ...
    def set_modal(self, value) -> None: ...
    modal: Incomplete

class ActionControlPanel(AutoExtensibleForm, form.EditForm):
    """A form to edit a portal action."""

    schema = IActionSchema
    ignoreContext: bool
    label: Incomplete

class NewActionControlPanel(AutoExtensibleForm, form.AddForm):
    """A form to add a new portal action."""

    schema = INewActionSchema
    ignoreContext: bool
    label: Incomplete
    def createAndAdd(self, data) -> None: ...
