from _typeshed import Incomplete
from plone.autoform.form import AutoExtensibleForm
from plone.base.interfaces import IMaintenanceSchema
from plone.memoize.view import memoize
from z3c.form import form

LIFETIME: bool
logger: Incomplete

class MaintenanceControlPanel(AutoExtensibleForm, form.EditForm):
    """A simple form to pack the databases."""

    schema = IMaintenanceSchema
    id: str
    label: Incomplete
    description: Incomplete
    form_name: Incomplete
    control_panel_view: str
    template: Incomplete
    @memoize
    def portal(self): ...
    status: Incomplete
    def handle_pack_action(self, action) -> None: ...
    def handle_shutdown_action(self, action): ...
    def handle_restart_action(self, action): ...
    def available(self): ...
    def isRestartable(self): ...
    def isShutdownable(self): ...
    def isDevelopmentMode(self): ...
    def coreVersions(self): ...
    def dbName(self): ...
    def dbSize(self): ...
