from _typeshed import Incomplete
from plone.app.registry.browser import controlpanel
from plone.memoize.instance import memoize

HAS_PAE: bool

class OverviewControlPanel(controlpanel.RegistryEditForm):
    template: Incomplete
    base_category: str
    ignored_categories: str
    def __call__(self): ...
    @memoize
    def cptool(self): ...
    @memoize
    def migration(self): ...
    @memoize
    def core_versions(self): ...
    def pil(self): ...
    def server_info(self): ...
    def version_overview(self): ...
    def is_dev_mode(self): ...
    def upgrade_warning(self): ...
    def mailhost_warning(self): ...
    def timezone_warning(self):
        """Returns true, if the portal_timezone is not set in the registry."""
    def categories(self): ...
    def sublists(self, category): ...
