from Products.Five.browser import BrowserView

class ResourceRegistryControlPanelView(BrowserView):
    @property
    def bundles_data(self): ...
    def global_debug_mode(self): ...
    def debug_mode(self): ...
    def process_form(self) -> None: ...
