from _typeshed import Incomplete
from plone.autoform.form import AutoExtensibleForm
from plone.base.interfaces import ITypesSchema
from plone.memoize.instance import memoize
from z3c.form import form

def format_description(text, request=None): ...

VERSION_POLICIES: Incomplete

class TypesControlPanel(AutoExtensibleForm, form.EditForm):
    schema = ITypesSchema
    id: str
    label: Incomplete
    description: Incomplete
    form_name: Incomplete
    control_panel_view: str
    template: Incomplete
    behavior_name: str
    status: Incomplete
    def handleSave(self, action) -> None: ...
    def handleCancel(self, action) -> None: ...
    @property
    @memoize
    def type_id(self): ...
    @property
    @memoize
    def fti(self): ...
    def add_versioning_behavior(self, fti) -> None: ...
    def remove_versioning_behavior(self, fti) -> None: ...
    def __call__(self):
        """Perform the update and redirect if necessary, or render the page"""
    def versioning_policies(self): ...
    @memoize
    def selectable_types(self): ...
    def selected_type_title(self): ...
    def selected_type_description(self): ...
    def is_addable(self): ...
    def is_discussion_allowed(self): ...
    def current_versioning_policy(self): ...
    def is_searchable(self): ...
    def is_default_page_type(self): ...
    def is_redirect_links_enabled(self): ...
    @memoize
    def current_workflow(self): ...
    def available_workflows(self): ...
    @memoize
    def new_workflow(self): ...
    @memoize
    def have_new_workflow(self): ...
    @memoize
    def default_workflow(self, id_only: bool = True): ...
    @memoize
    def real_workflow(self, wf): ...
    @memoize
    def new_workflow_is_different(self): ...
    @memoize
    def new_workflow_is_none(self): ...
    def new_workflow_description(self): ...
    def new_workflow_available_states(self): ...
    def suggested_state_map(self): ...
