from _typeshed import Incomplete
from plone.dexterity.browser.base import DexterityExtensibleForm
from z3c.form import form

class DefaultEditForm(DexterityExtensibleForm, form.EditForm):
    success_message: Incomplete
    status: Incomplete
    def handleApply(self, action) -> None: ...
    def handleCancel(self, action) -> None: ...
    def nextURL(self): ...
    portal_type: Incomplete
    def update(self) -> None: ...
    def updateActions(self) -> None: ...
    @property
    def fti(self): ...
    @property
    def label(self): ...

DefaultEditView: Incomplete
