from Products.Five import BrowserView

__all__ = ["AuthenticatorView", "CustomCheckAuthenticator", "check", "createToken"]

def createToken(extra: str = "", manager=None): ...

class AuthenticatorView(BrowserView):
    def token(self, extra: str = ""): ...
    def authenticator(self, extra: str = "", name: str = "_authenticator"): ...
    def verify(self, extra: str = "", name: str = "_authenticator"): ...

def check(
    request, extra: str = "", name: str = "_authenticator", manager=None
) -> None: ...
def CustomCheckAuthenticator(extra: str = "", name: str = "_authenticator"): ...
