from _typeshed import Incomplete

SAFE_WRITE_KEY: str
BTREE_TYPES: Incomplete
LOGGER: Incomplete

class protect:
    checkers: Incomplete
    def __init__(self, *checkers) -> None: ...
    def __call__(self, callable): ...

def addTokenToUrl(url, req=None, manager=None): ...
def getRootKeyManager(root): ...
def getRoot(context): ...
def safeWrite(obj, request=None) -> None: ...
