from plone.memoize.instance import memoize
from Products.Five import BrowserView

class PASInfoView(BrowserView):
    def checkExtractorForInterface(self, interface): ...
    @memoize
    def hasLoginPasswordExtractor(self): ...
    @memoize
    def hasOpenIDExtractor(self): ...
    def hasOpenIDdExtractor(self): ...
    def __call__(self) -> None: ...
