from _typeshed import Incomplete
from Products.Five import BrowserView

class PASSearchView(BrowserView):
    @staticmethod
    def extractCriteriaFromRequest(request): ...
    @staticmethod
    def merge(results, key): ...
    def sort(self, results, sort_key): ...
    pas: Incomplete
    def searchUsers(self, sort_by=None, **criteria): ...
    def searchUsersByRequest(self, request, sort_by=None): ...
    def searchGroups(self, sort_by=None, **criteria): ...
    def searchGroupsByRequest(self, request): ...
    def getPhysicalPath(self): ...
    def __call__(self) -> None: ...
