from _typeshed import Incomplete

log: Incomplete
BEHAVIOR_LIST: Incomplete

def enable_richtext_behavior(self) -> None: ...
def upgrade_attribute_storage(context) -> None: ...
def remove_event_listing_settings(context) -> None: ...
