from _typeshed import Incomplete
from Persistence import Persistent

class Lexicon(Persistent):
    def __init__(self, *pipeline) -> None: ...
    def clear(self) -> None:
        """Empty the lexicon."""
    def length(self) -> None:
        """Return the number of unique terms in the lexicon."""
    def words(self): ...
    def wids(self): ...
    def items(self): ...
    def sourceToWordIds(self, text): ...
    def termToWordIds(self, text): ...
    def parseTerms(self, text): ...
    def isGlob(self, word): ...
    def get_word(self, wid): ...
    def get_wid(self, word): ...
    def globToWordIds(self, pattern): ...

class Splitter:
    rx: Incomplete
    rxGlob: Incomplete
    def process(self, lst): ...
    def processGlob(self, lst): ...

class CaseNormalizer:
    def process(self, lst): ...

class StopWordRemover:
    dict: Incomplete
    def process(self, lst): ...

class StopWordAndSingleCharRemover(StopWordRemover):
    dict: Incomplete
