class NBest:
    def __init__(self, n) -> None:
        """Build an NBest object to remember the N best-scoring objects."""
    def __len__(self) -> int: ...
    def capacity(self): ...
    def add(self, item, score) -> None: ...
    def addmany(self, sequence) -> None: ...
    def getbest(self): ...
    def pop_smallest(self): ...
