from Products.ZCTextIndex.BaseIndex import BaseIndex

class OkapiIndex(BaseIndex):
    K1: float
    B: float
    def __init__(self, lexicon) -> None: ...
    def index_doc(self, docid, text): ...
    def unindex_doc(self, docid) -> None: ...
    def query_weight(self, terms): ...
