class QueryError(Exception): ...
class ParseError(Exception): ...

class ParseTreeNode:
    def __init__(self, value) -> None: ...
    def nodeType(self): ...
    def getValue(self): ...
    def terms(self): ...
    def executeQuery(self, index) -> None: ...

class NotNode(ParseTreeNode):
    def terms(self): ...
    def executeQuery(self, index) -> None: ...

class AndNode(ParseTreeNode):
    def executeQuery(self, index): ...

class OrNode(ParseTreeNode):
    def executeQuery(self, index): ...

class AtomNode(ParseTreeNode):
    def terms(self): ...
    def executeQuery(self, index): ...

class PhraseNode(AtomNode):
    def executeQuery(self, index): ...

class GlobNode(AtomNode):
    def executeQuery(self, index): ...
