from _typeshed import Incomplete

class PipelineElementFactory:
    def __init__(self) -> None: ...
    def registerFactory(self, group, name, factory) -> None: ...
    def getFactoryGroups(self): ...
    def getFactoryNames(self, group): ...
    def instantiate(self, group, name): ...

element_factory: Incomplete
