from _typeshed import Incomplete

unicode = str

class Token:
    text: Incomplete
    def __init__(self, text) -> None: ...

class QueryParser:
    def __init__(self, lexicon) -> None: ...
    def parseQuery(self, query): ...
    def getIgnored(self): ...
    def parseQueryEx(self, query): ...
