from _typeshed import Incomplete

class DefaultJsonSchemaProvider:
    field: Incomplete
    context: Incomplete
    request: Incomplete
    def __init__(self, field, context, request) -> None: ...
    def additional(self):
        """Additional info for field."""
    def get_title(self): ...
    def get_description(self): ...
    def get_schema(self):
        """Get jsonschema for field.

        You should override `additional` method to provide more properties
        about the field."""
    def get_type(self) -> None: ...
    def get_factory(self) -> None: ...
    def get_widget(self): ...
    def get_widget_params(self): ...
    def get_multilingual_directives(self): ...

class BytesLineJsonSchemaProvider(DefaultJsonSchemaProvider):
    def get_type(self): ...
    def get_factory(self): ...

class TextLineJsonSchemaProvider(DefaultJsonSchemaProvider):
    def additional(self): ...
    def get_type(self): ...
    def get_factory(self): ...

class TextJsonSchemaProvider(TextLineJsonSchemaProvider):
    def get_widget(self): ...
    def get_factory(self): ...

class EmailJsonSchemaProvider(TextLineJsonSchemaProvider):
    def get_widget(self): ...
    def get_factory(self): ...

class PasswordJsonSchemaProvider(TextLineJsonSchemaProvider):
    def get_widget(self): ...
    def get_factory(self): ...

class URIJsonSchemaProvider(TextLineJsonSchemaProvider):
    def get_widget(self): ...
    def get_factory(self): ...

class ASCIIJsonSchemaProvider(TextLineJsonSchemaProvider): ...
class ASCIILineJsonSchemaProvider(TextLineJsonSchemaProvider): ...

class FloatJsonSchemaProvider(DefaultJsonSchemaProvider):
    def get_type(self): ...
    def additional(self): ...
    def get_factory(self): ...

class DecimalJsonSchemaProvider(FloatJsonSchemaProvider): ...

class IntegerJsonSchemaProvider(FloatJsonSchemaProvider):
    def get_type(self): ...
    def get_factory(self): ...

class BoolJsonSchemaProvider(DefaultJsonSchemaProvider):
    def get_type(self): ...
    def get_factory(self): ...

class CollectionJsonSchemaProvider(DefaultJsonSchemaProvider):
    def get_type(self): ...
    def get_factory(self): ...
    def get_items(self):
        """Get items properties."""
    def additional(self): ...

class ListJsonSchemaProvider(CollectionJsonSchemaProvider):
    def additional(self): ...

class SetJsonSchemaProvider(CollectionJsonSchemaProvider):
    def additional(self): ...

class TupleJsonSchemaProvider(SetJsonSchemaProvider): ...

class ChoiceJsonSchemaProvider(DefaultJsonSchemaProvider):
    should_render_choices: bool
    def get_type(self): ...
    def get_factory(self): ...
    def additional(self): ...

class ObjectJsonSchemaProvider(DefaultJsonSchemaProvider):
    prefix: str
    def get_type(self): ...
    def get_factory(self): ...
    def get_properties(self): ...
    def additional(self): ...

class DictJsonSchemaProvider(DefaultJsonSchemaProvider):
    def get_type(self): ...
    def additional(self): ...

class RichTextJsonSchemaProvider(DefaultJsonSchemaProvider):
    prefix: str
    def get_type(self): ...
    def get_widget(self): ...
    def get_factory(self): ...

class DateJsonSchemaProvider(DefaultJsonSchemaProvider):
    def get_type(self): ...
    def additional(self): ...
    def get_widget(self): ...
    def get_factory(self): ...

class DatetimeJsonSchemaProvider(DateJsonSchemaProvider):
    def get_widget(self): ...
    def get_factory(self): ...

class SubjectsFieldJsonSchemaProvider(ChoiceJsonSchemaProvider): ...

class JSONFieldSchemaProvider(DefaultJsonSchemaProvider):
    def get_type(self): ...
    def get_widget(self): ...
    def get_factory(self): ...
