from _typeshed import Incomplete

class BaseTransformEvent:
    request: Incomplete
    def __init__(self, request) -> None: ...

class BaseSingleTransformEvent(BaseTransformEvent):
    name: Incomplete
    handler: Incomplete
    def __init__(self, request, name, handler) -> None: ...

class BeforeTransforms(BaseTransformEvent): ...
class AfterTransforms(BaseTransformEvent): ...
class BeforeSingleTransform(BaseSingleTransformEvent): ...
class AfterSingleTransform(BaseSingleTransformEvent): ...
