from _typeshed import Incomplete

class DefaultPortletPermissionChecker:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def __call__(self) -> None: ...

class UserPortletPermissionChecker:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def __call__(self) -> None: ...

class GroupDashboardPortletPermissionChecker:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def __call__(self) -> None: ...
