class PloneApiError(Exception): ...
class MissingParameterError(PloneApiError): ...
class InvalidParameterError(PloneApiError): ...
class CannotGetPortalError(PloneApiError): ...
class UserNotFoundError(PloneApiError): ...
class GroupNotFoundError(PloneApiError): ...
