from _typeshed import Incomplete

class SearchHandler:
    """Executes a catalog search based on a query dict, and returns
    JSON compatible results.
    """

    context: Incomplete
    request: Incomplete
    catalog: Incomplete
    def __init__(self, context, request) -> None: ...
    def quote_chars(self, query): ...
    def search(self, query=None): ...
    def filter_types(self, types): ...
    def filter_query(self, query): ...
