from _typeshed import Incomplete
from zope.pagetemplate.engine import TrustedAppPT
from zope.pagetemplate.pagetemplatefile import PageTemplateFile

def getEngine(): ...

class ViewPageTemplateFile(TrustedAppPT, PageTemplateFile):
    """Page Template used as class variable of views defined as Python classes."""

    content_type: Incomplete
    def __init__(self, filename, _prefix=None, content_type=None) -> None: ...
    def getId(self): ...
    id: Incomplete
    def __call__(self, /, __instance, *args, **keywords): ...
    def pt_getEngine(self): ...
    def pt_getContext(self, instance, request, **kw): ...
    def __get__(self, instance, type): ...

class ViewMapper:
    ob: Incomplete
    request: Incomplete
    def __init__(self, ob, request) -> None: ...
    def __getitem__(self, name): ...

class BoundPageTemplate:
    def __init__(self, pt, ob) -> None: ...
    macros: Incomplete
    filename: Incomplete
    __parent__: Incomplete
    def __call__(self, *args, **kw): ...
    def __setattr__(self, name, v) -> None: ...

ZopeTwoPageTemplateFile = ViewPageTemplateFile
