from ..portlets import base
from _typeshed import Incomplete
from plone.memoize.instance import memoize
from plone.portlets.interfaces import IPortletDataProvider

class ILoginPortlet(IPortletDataProvider):
    """A portlet which can render a login form."""

class Assignment(base.Assignment):
    title: Incomplete

class Renderer(base.Renderer):
    membership: Incomplete
    context_state: Incomplete
    portal_state: Incomplete
    pas_info: Incomplete
    def __init__(self, context, request, view, manager, data) -> None: ...
    def show(self): ...
    @property
    def available(self): ...
    def login_form(self): ...
    def mail_password_form(self): ...
    def login_name(self): ...
    def login_password(self): ...
    def join_action(self): ...
    def can_register(self): ...
    def can_request_password(self): ...
    @memoize
    def auth(self, _marker=None): ...
    def update(self) -> None: ...
    render: Incomplete

class AddForm(base.NullAddForm):
    def create(self): ...
