from _typeshed import Incomplete

class EditView:
    """Marker interface edit view."""

    context: Incomplete
    request: Incomplete
    adapted: Incomplete
    context_url: Incomplete
    def __init__(self, context, request) -> None: ...
    def __call__(self, SAVE=None, add=(), remove=()): ...
    def getAvailableInterfaceNames(self): ...
    def getDirectlyProvidedNames(self): ...
    def getInterfaceNames(self): ...
    def update(self, add, remove) -> None: ...
