from _typeshed import Incomplete

FILTERS: Incomplete

class PersistentResourceDirectory:
    """A resource directory stored in the ZODB.

    It is assumed that directories provide IObjectManager
    and that files are instances of OFS.Image.File.
    """

    context: Incomplete
    def __init__(self, context=None) -> None: ...
    def publishTraverse(self, request, name): ...
    def __getitem__(self, name): ...
    def __setitem__(self, name, item) -> None: ...
    def __delitem__(self, name) -> None: ...
    def __contains__(self, name) -> bool: ...
    def openFile(self, path): ...
    def readFile(self, path): ...
    def listDirectory(self): ...
    def isDirectory(self, path): ...
    def isFile(self, path): ...
    def rename(self, oldName, newName) -> None: ...
    def exportZip(self, out) -> None: ...
    def makeDirectory(self, path) -> None: ...
    def writeFile(self, path, data) -> None: ...
    def importZip(self, f) -> None: ...

class FilesystemResourceDirectory:
    """A resource directory based on files in the filesystem."""

    __allow_access_to_unprotected_subobjects__: bool
    directory: Incomplete
    def __init__(self, directory, name=None, parent=None) -> None: ...
    @property
    def __parent__(self): ...
    @__parent__.setter
    def __parent__(self, value) -> None: ...
    def __bytes__(self) -> bytes: ...
    def publishTraverse(self, request, name): ...
    def __contains__(self, name) -> bool: ...
    def __getitem__(self, name): ...
    def openFile(self, path): ...
    def readFile(self, path): ...
    def listDirectory(self): ...
    def isDirectory(self, path): ...
    def isFile(self, path): ...
    def exportZip(self, out) -> None: ...
