class RequestCache(dict):
    def get(self, key, default=None): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def clear(self) -> None: ...
    def stats(self): ...
