from z3c.form.browser.checkbox import CheckBoxWidget

class ReverseCheckBoxWidget(CheckBoxWidget):
    """Checkbox widget where you uncheck the options you want to select."""
    def isChecked(self, term): ...
    def extract(self, default=...): ...

def ReverseCheckBoxFieldWidget(field, request): ...
