from _typeshed import Incomplete

class plone_outputfilters_html_to_html:
    inputs: Incomplete
    output: str
    config_metadata: Incomplete
    def __init__(self, name=None) -> None: ...
    def name(self): ...
    def convert(self, orig, data, **kwargs): ...

def register(): ...
