from _typeshed import Incomplete
from plone.memoize import view
from Products.Five.browser import BrowserView

class EventListing(BrowserView):
    now: Incomplete
    default_context: Incomplete
    is_collection: bool
    b_size: Incomplete
    b_start: Incomplete
    orphan: Incomplete
    mode: Incomplete
    tags: Incomplete
    searchable_text: Incomplete
    path: Incomplete
    uid: Incomplete
    def __init__(self, context, request) -> None: ...
    @property
    def show_filter(self): ...
    @property
    def date(self): ...
    @view.memoize
    def events(self, ret_mode=..., expand: bool = True, batch: bool = True): ...
    @property
    def ical(self) -> None: ...
    @property
    def ical_url(self): ...
    def formatted_date(self, occ): ...
    def date_speller(self, date): ...
    @property
    def header_string(self): ...
    @property
    def mode_all_url(self): ...
    @property
    def mode_future_url(self): ...
    @property
    def mode_past_url(self): ...
    @property
    def mode_day_url(self): ...
    @property
    def mode_week_url(self): ...
    @property
    def mode_month_url(self): ...
    @property
    def next_day_url(self): ...
    @property
    def today_url(self): ...
    @property
    def prev_day_url(self): ...
    @property
    def next_week_url(self): ...
    @property
    def this_week_url(self): ...
    @property
    def prev_week_url(self): ...
    @property
    def next_month_url(self): ...
    @property
    def this_month_url(self): ...
    @property
    def prev_month_url(self): ...

class EventListingIcal(EventListing):
    def __call__(self, *args, **kwargs): ...

class EventEventListing(EventListing):
    """This is an EventListing for an individual event, to list all
    occurrences batched and navigatable with all the features, the EventListing
    offers.
    """

    uid: Incomplete
    def __init__(self, context, request) -> None: ...
