from _typeshed import Incomplete
from zope.interface import Interface

class ITransactionManager(Interface):
    explicit: Incomplete
    def begin(self) -> None: ...
    def get(self) -> None: ...
    def commit(self) -> None: ...
    def abort(self) -> None: ...
    def doom(self) -> None: ...
    def isDoomed(self) -> None: ...
    def savepoint(self, optimistic: bool = False) -> None: ...
    def registerSynch(self, synch) -> None: ...
    def unregisterSynch(self, synch) -> None: ...
    def clearSynchs(self) -> None: ...
    def registeredSynchs(self) -> None: ...
    def attempts(self, number: int = 3) -> None: ...
    def run(self, func=None, tries: int = 3) -> None: ...

class ITransaction(Interface):
    user: Incomplete
    description: Incomplete
    extension: Incomplete
    def commit(self) -> None: ...
    def abort(self) -> None: ...
    def doom(self) -> None: ...
    def savepoint(self, optimistic: bool = False) -> None: ...
    def join(self, datamanager) -> None: ...
    def note(self, text) -> None: ...
    def setExtendedInfo(self, name, value) -> None: ...
    def addBeforeCommitHook(self, hook, args=(), kws=None) -> None: ...
    def getBeforeCommitHooks(self) -> None: ...
    def addAfterCommitHook(self, hook, args=(), kws=None) -> None: ...
    def getAfterCommitHooks(self) -> None: ...
    def addBeforeAbortHook(self, hook, args=(), kws=None) -> None: ...
    def getBeforeAbortHooks(self) -> None: ...
    def addAfterAbortHook(self, hook, args=(), kws=None) -> None: ...
    def getAfterAbortHooks(self) -> None: ...
    def set_data(self, ob, data) -> None: ...
    def data(self, ob) -> None: ...
    def isRetryableError(self, error) -> None: ...

class IDataManager(Interface):
    transaction_manager: Incomplete
    def abort(self, transaction) -> None: ...
    def tpc_begin(self, transaction) -> None: ...
    def commit(self, transaction) -> None: ...
    def tpc_vote(self, transaction) -> None: ...
    def tpc_finish(self, transaction) -> None: ...
    def tpc_abort(self, transaction) -> None: ...
    def sortKey(self) -> None: ...

class ISavepointDataManager(IDataManager):
    def savepoint(self) -> None: ...

class IRetryDataManager(IDataManager):
    def should_retry(self, exception) -> None: ...

class IDataManagerSavepoint(Interface):
    def rollback(self) -> None: ...

class ISavepoint(Interface):
    def rollback(self) -> None: ...
    valid: Incomplete

class InvalidSavepointRollbackError(Exception): ...

class ISynchronizer(Interface):
    def beforeCompletion(self, transaction) -> None: ...
    def afterCompletion(self, transaction) -> None: ...
    def newTransaction(self, transaction) -> None: ...

class TransactionError(Exception): ...
class TransactionFailedError(TransactionError): ...
class DoomedTransaction(TransactionError): ...
class TransientError(TransactionError): ...
class NoTransaction(TransactionError): ...
class AlreadyInTransaction(TransactionError): ...
