from _typeshed import Incomplete

class WeakSet:
    data: Incomplete
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, obj) -> bool: ...
    def add(self, obj) -> None: ...
    def remove(self, obj) -> None: ...
    def clear(self) -> None: ...
    def map(self, f) -> None: ...
    def as_weakref_list(self): ...
