from _typeshed import Incomplete

PLONE_RELATION_INDEXES: Incomplete

def relation_catalog_factory(): ...
def add_relations(context) -> None: ...
def add_intids(context) -> None: ...
def installRelations(context): ...
