from _typeshed import Incomplete

class CMFContentSearchSource:
    context: Incomplete
    intid_utility: Incomplete
    def __init__(self, context) -> None: ...
    def __contains__(self, term) -> bool: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def getTerm(self, obj): ...
    def getTermByToken(self, value): ...
    def search(self, query_string): ...
