from persistent import Persistent

class ViewletSettingsStorage(Persistent):
    def __init__(self) -> None: ...
    def getOrder(self, name, skinname): ...
    def setOrder(self, name, skinname, order) -> None: ...
    def getHidden(self, name, skinname): ...
    def setHidden(self, name, skinname, hidden) -> None: ...
    def getDefault(self, name): ...
    def setDefault(self, name, skinname) -> None: ...
