from _typeshed import Incomplete

MAXCHUNKSIZE: Incomplete

class BytesStorable:
    def store(self, data, blob) -> None: ...

class TextStorable(BytesStorable):
    def store(self, data, blob) -> None: ...

class UnicodeStorable(TextStorable): ...
class StringStorable(BytesStorable): ...

class FileChunkStorable:
    def store(self, data, blob) -> None: ...

class FileDescriptorStorable:
    def store(self, data, blob) -> None: ...

class BufferedReaderStorable:
    def store(self, data, blob) -> None: ...

class FileUploadStorable:
    def store(self, data, blob) -> None: ...

class PDataStorable:
    def store(self, pdata, blob) -> None: ...

class Zope2FileUploadStorable:
    def store(self, data, blob) -> None: ...
