from _typeshed import Incomplete

class EmDashAdder:
    order: int
    def __init__(self, context, request) -> None: ...
    def is_enabled(self): ...
    pattern: Incomplete
    def __call__(self, data): ...
