from _typeshed import Incomplete

class LazyDict:
    """cached lookup via adapter"""

    context: Incomplete
    def __init__(self, context) -> None: ...
    def __getitem__(self, key): ...

class Interpolator:
    def __init__(self, context) -> None: ...
    def __call__(self, s): ...
