from plone.app.contenttypes.browser.utils import Utils

class FileView(Utils):
    def is_videotype(self): ...
    def is_audiotype(self): ...
    def human_readable_size(self): ...
    def icon(self): ...
