from _typeshed import Incomplete
from plone.memoize.view import memoize
from Products.Five import BrowserView

class FolderView(BrowserView):
    text_class: Incomplete
    @property
    def plone_view(self): ...
    @property
    def portal_state(self): ...
    @property
    def pas_member(self): ...
    @property
    def b_size(self): ...
    @property
    def b_start(self): ...
    def results(self, **kwargs):
        """Return a content listing based result set with contents of the
        folder.

        :param **kwargs: Any keyword argument, which can be used for catalog
                         queries.
        :type  **kwargs: keyword argument

        :returns: plone.app.contentlisting based result set.
        :rtype: ``plone.app.contentlisting.interfaces.IContentListing`` based
                sequence.
        """
    def batch(self): ...
    def normalizeString(self, text): ...
    def toLocalizedTime(self, time, long_format=None, time_only=None): ...
    @property
    def friendly_types(self): ...
    @property
    def isAnon(self): ...
    @property
    def navigation_root_url(self): ...
    @property
    def use_view_action(self): ...
    @property
    def show_about(self): ...
    @property
    def text(self): ...
    @property
    def tabular_fields(self): ...
    def tabular_field_label(self, field):
        """Return the internationalized label (Message object) corresponding
        to the field.
        """
    def tabular_fielddata(self, item, fieldname): ...
    def is_event(self, obj): ...
    def formatted_date(self, item): ...
    @property
    @memoize
    def album_images(self):
        """Get all images within this folder."""
    @property
    @memoize
    def album_folders(self):
        """Get all folders within this folder."""
    @property
    def album_random_image(self):
        """Get random image from this folder."""
    @property
    def album_number_images(self):
        """Get number of images from this folder."""
    @property
    def no_items_message(self): ...
    @memoize
    def get_thumb_scale_table(self): ...
    @memoize
    def get_thumb_scale_list(self): ...
    @memoize
    def get_thumb_scale_summary(self): ...
    def show_icons(self): ...
