from _typeshed import Incomplete
from Products.PortalTransforms.libtransforms.commandtransform import commandtransform

class rtf_to_xml(commandtransform):
    inputs: Incomplete
    output: str
    binaryName: str
    def __init__(self) -> None: ...
    def convert(self, data, cache, **kwargs): ...
    def invokeCommand(self, tmpdir, fullname): ...

def register(): ...
