from _typeshed import Incomplete

class TextPreToHTML:
    """simple transform which wraps raw text into a <pre> tag"""

    inputs: Incomplete
    output: str
    config_metadata: Incomplete
    def __init__(self, name=None) -> None: ...
    def name(self): ...
    def __getattr__(self, attr): ...
    def convert(self, orig, data, **kwargs): ...

def register(): ...
