from _typeshed import Incomplete

class TextToHTML:
    """simple transform which wrap raw text in a verbatim environment"""

    output: str
    config: Incomplete
    config_metadata: Incomplete
    def __init__(self, name=None, inputs=("text/plain",)) -> None: ...
    def name(self): ...
    def __getattr__(self, attr): ...
    def convert(self, orig, data, **kwargs): ...

def register(): ...
