def register_mimetype(context, mimetype) -> None: ...
def unregister_mimetype(context, mimetype) -> None: ...
def register_transform(context, transform) -> None: ...
def unregister_transform(context, transform) -> None: ...
def register_transform_policy(context, output_mimetype, required_transform) -> None: ...
def unregister_transform_policy(context, output_mimetype) -> None: ...
def install_mimetype_and_transforms(context) -> None:
    """register mimetype and transformations for captioned images"""

def uninstall_mimetype_and_transforms(context) -> None:
    """unregister mimetype and transformations for captioned images"""

def importVarious(context) -> None: ...
