from _typeshed import Incomplete
from OFS.SimpleItem import SimpleItem
from Products.Five import BrowserView

class PortletAdding(SimpleItem, BrowserView):
    context: Incomplete
    request: Incomplete
    id: str
    def add(self, content) -> None:
        """Add the rule to the context"""
    @property
    def referer(self): ...
    def nextURL(self): ...
    def renderAddButton(self) -> None: ...
    def namesAccepted(self): ...
    def nameAllowed(self): ...
    @property
    def contentName(self) -> None: ...
    def addingInfo() -> None: ...
    def isSingleMenuItem(): ...
    def hasCustomAddView(): ...
