from _typeshed import Incomplete
from Acquisition import Explicit
from plone.memoize.view import memoize
from Products.Five.browser import BrowserView

class EditPortletManagerRenderer(Explicit):
    """Render a portlet manager in edit mode.

    This is the generic renderer, which delegates to the view to determine
    which assignments to display.

    """

    template: Incomplete
    __parent__: Incomplete
    manager: Incomplete
    context: Incomplete
    request: Incomplete
    def __init__(self, context, request, view, manager) -> None: ...
    @property
    def visible(self): ...
    def filter(self, portlets): ...
    def update(self) -> None: ...
    def render(self): ...
    @property
    def view_name(self): ...
    def normalized_manager_name(self): ...
    def baseUrl(self): ...
    def portlets(self): ...
    def portlets_for_assignments(self, assignments, manager, base_url): ...
    def addable_portlets(self): ...
    @memoize
    def referer(self): ...
    @memoize
    def url_quote_referer(self): ...
    @memoize
    def key(self): ...
    @memoize
    def context_url(self): ...

class ContextualEditPortletManagerRenderer(EditPortletManagerRenderer):
    """Render a portlet manager in edit mode for contextual portlets"""

    template: Incomplete
    def __init__(self, context, request, view, manager) -> None: ...
    def blacklist_status_action(self): ...
    def manager_name(self): ...
    def context_blacklist_status(self): ...
    def group_blacklist_status(self, check_parent: bool = False): ...
    def content_type_blacklist_status(self, check_parent: bool = False): ...
    def parent_blacklist_status(self, category): ...
    def inherited_portlets(self):
        """Return the list of portlets inherited by the current context.

        Invisible (hidden) portlets are excluded.

        """
    def global_portlets(self, category, prefix):
        """Return the list of global portlets from a given category for the current context.

        Invisible (hidden) portlets are excluded.

        """
    def group_portlets(self):
        """Return the list of global portlets from the group category for the
        current context."""
    def content_type_portlets(self):
        """Return the list of global portlets from the content type category for
        the current context."""

class DashboardEditPortletManagerRenderer(EditPortletManagerRenderer):
    """Render a portlet manager in edit mode for the dashboard"""

class ManagePortletAssignments(BrowserView):
    """Utility views for managing portlets for a particular column"""
    def authorize(self) -> None: ...
    def finish_portlet_change(self): ...
    def move_portlet_up(self, name): ...
    def move_portlet_down(self, name): ...
    def delete_portlet(self, name): ...
    def toggle_visibility(self, name): ...
