from Products.Five import BrowserView

def get_url(item): ...
def get_id(item): ...
def get_view_url(context): ...

class CatalogSiteMap(BrowserView):
    def siteMap(self): ...

class CatalogNavigationTabs(BrowserView):
    def topLevelTabs(self, actions=None, category: str = "portal_tabs"): ...
    def customize_entry(self, entry, brain=None) -> None:
        """a little helper to enlarge customizability."""

class CatalogNavigationBreadcrumbs(BrowserView):
    def breadcrumbs(self): ...

class PhysicalNavigationBreadcrumbs(BrowserView):
    def breadcrumbs(self): ...
    def customize_entry(self, entry, context=None) -> None:
        """a little helper to enlarge customizability."""

class RootPhysicalNavigationBreadcrumbs(BrowserView):
    def breadcrumbs(self): ...
