from plone.memoize.view import memoize
from Products.Five import BrowserView

class Plone(BrowserView):
    @memoize
    def uniqueItemIndex(self, pos: int = 0):
        """Return an index iterator."""
    def toLocalizedTime(self, time, long_format=None, time_only=None):
        """Convert time to localized time"""
    def toLocalizedSize(self, size):
        """Convert an integer to a localized size string"""
    def showToolbar(self):
        """Determine if the editable border should be shown"""
    def normalizeString(self, text):
        """Normalizes a title to an id."""
    def cropText(self, text, length, ellipsis: str = "..."):
        """Crop text on a word boundary"""
    @property
    def human_readable_size(self): ...
    def site_encoding(self): ...
    def getCurrentUrl(self): ...
    def isDefaultPageInFolder(self): ...
    def isStructuralFolder(self): ...
    def navigationRootPath(self): ...
    def navigationRootUrl(self): ...
    def getParentObject(self): ...
    def getCurrentFolder(self): ...
    def getCurrentFolderUrl(self): ...
    @memoize
    def getCurrentObjectUrl(self): ...
    @memoize
    def isFolderOrFolderDefaultPage(self): ...
    @memoize
    def isPortalOrPortalDefaultPage(self): ...
    @memoize
    def getViewTemplateId(self): ...
    @memoize
    def patterns_settings(self): ...
