from _typeshed import Incomplete
from plone.restapi.services import Service

def check_security(context) -> None: ...

class TypesInfo:
    context: Incomplete
    request: Incomplete
    def __init__(self, context, request) -> None: ...
    def __call__(self, expand: bool = False): ...

class TypesInfoRoot(TypesInfo): ...

class TypesGet(Service):
    params: Incomplete
    def __init__(self, context, request) -> None: ...
    def publishTraverse(self, request, name): ...
    def reply(self): ...
    content_type: str
    def reply_for_type(self): ...
    def reply_for_field(self): ...
    def reply_for_fieldset(self): ...
