from _typeshed import Incomplete
from plone.restapi.services import Service

class TypesPut(Service):
    params: Incomplete
    def __init__(self, context, request) -> None: ...
    def publishTraverse(self, request, name): ...
    def update_layouts(self, name, data) -> None: ...
    def remove_fieldsets(self, ctype, data) -> None: ...
    def add_fieldsets(self, ctype, data) -> None: ...
    def remove_fields(self, ctype, data) -> None: ...
    def add_fields(self, ctype, data) -> None: ...
    def update_fieldsets(self, ctype, data) -> None: ...
    def update_fields(self, ctype, data) -> None: ...
    def reply(self): ...
