from _typeshed import Incomplete
from plone.restapi.services import Service

class TypesUpdate(Service):
    params: Incomplete
    def __init__(self, context, request) -> None: ...
    def publishTraverse(self, request, name): ...
    def reply(self): ...
    def reply_for_fieldset(self, name, fieldset_name, data, create: bool = False): ...
    def reply_for_field(self, name, field_name, data, create: bool = False): ...
