__all__ = ["loadFile", "loadString", "serializeModel", "serializeSchema", "xmlSchema"]

def xmlSchema(filename, schema: str = "", policy: str = "", _frame: int = 2): ...
def loadFile(filename, reload: bool = False, policy: str = "", _frame: int = 2): ...
def loadString(model, policy: str = ""): ...
def serializeSchema(schema, name: str = ""): ...
def serializeModel(model): ...
