from _typeshed import Incomplete

class DefaultFromUnicode:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def fromUnicode(self, value): ...

class DefaultToUnicode:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def toUnicode(self, value): ...

class DateFromUnicode:
    format: str
    context: Incomplete
    def __init__(self, context) -> None: ...
    def fromUnicode(self, value): ...

class DatetimeFromUnicode:
    format: str
    context: Incomplete
    def __init__(self, context) -> None: ...
    def fromUnicode(self, value): ...

class InterfaceFieldFromUnicode:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def fromUnicode(self, value): ...

class InterfaceFieldToUnicode:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def toUnicode(self, value): ...

class ObjectFromUnicode:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def fromUnicode(self, value): ...

class BytesToUnicode:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def toUnicode(self, value): ...
