from _typeshed import Incomplete

__all__ = ["parse"]

class SupermodelParseError(Exception):
    args: Incomplete
    def __init__(self, orig_exc, fname, element, tb) -> None: ...

class DefaultSchemaPolicy:
    def module(self, schemaName, tree): ...
    def bases(self, schemaName, tree): ...
    def name(self, schemaName, tree): ...

def parse(source, policy: str = ""): ...
