from _typeshed import Incomplete
from collections.abc import MutableMapping
from persistent.dict import PersistentDict
from zope.interface import Interface

logger: Incomplete
KEEP_SCALE_MILLIS: Incomplete
number_types: Incomplete

class IImageScaleStorage(Interface):
    """This is an adapter for image content which can store, retrieve and
    generate image scale data. It provides a dictionary interface to
    existing image scales using the scale id as key. To find or create a
    scale based on its scaling parameters use the :meth:`scale` method."""
    def __init__(context, modified=None) -> None:
        """Adapt the given context item and optionally provide a callable
        to return a representation of the last modification date, which
        can be used to invalidate stored scale data on update."""
    def pre_scale(**parameters) -> None:
        """Pre-register a unique id for a scale, without actually scaling.

        In other words: no use of Pillow allowed.
        """
    def scale(**parameters) -> None:
        """Find image scale data for the given parameters or create it.

        We will look for an IImageScaleFactory for the context, and pass
        the parameters.  This factory is expected to return a tuple
        containing a representation of the actual image scale data (i.e.
        a string or file-like object) as well as the image's format and
        dimensions.  For convenience, this happens to match the return
        value of `scaleImage`, but makes it possible to use different
        storages, i.e. ZODB blobs"""
    def __getitem__(uid) -> None:
        """Find image scale data based on its uid."""
    def get_or_generate(uid) -> None:
        """Find image scale data based on its uid, or generate it.

        Only uids pre-generated by the pre_scale method should be accepted.

        Outdated scales may be returned: this method is called when requesting a scale
        on a cached, unique url.  An old cached page may still point to this.
        """

class ScalesDict(PersistentDict):
    def raise_conflict(self, saved, new) -> None: ...

class AnnotationStorage(MutableMapping):
    """An abstract storage for image scale data using annotations and
    implementing :class:`IImageScaleStorage`. Image data is stored as an
    annotation on the object container, i.e. the image. This is needed
    since not all images are themselves annotatable."""

    context: Incomplete
    modified: Incomplete
    def __init__(self, context, modified=None) -> None: ...
    @property
    def modified_time(self): ...
    @property
    def storage(self): ...
    def hash(self, **parameters): ...
    def unhash(self, hash_key): ...
    def get_info_by_hash(self, hash): ...
    def hash_key(self, **parameters): ...
    def pre_scale(self, **parameters): ...
    def generate_scale(self, uid=None, **parameters): ...
    def scale(self, **parameters): ...
    def get_or_generate(self, name): ...
    def __getitem__(self, uid): ...
    def __setitem__(self, id, scale) -> None: ...
    def __delitem__(self, uid) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def keys(self): ...
    def has_key(self, uid): ...
    __contains__ = has_key
    def clear(self) -> None: ...
