from plone.restapi.serializer.controlpanels import ControlpanelSerializeToJson

class DexterityTypesControlpanelSerializeToJson(ControlpanelSerializeToJson):
    def count(self, portal_type): ...
    def serialize_item(self, proxy): ...
    def __call__(self, item=None): ...
