from _typeshed import Incomplete
from plone.restapi.services import Service

class PrincipalsGet(Service):
    search_term: Incomplete
    def reply(self): ...
    def serialize_principals(self, principals): ...
    def user_search_results(self): ...
    def group_search_results(self): ...
