from _typeshed import Incomplete
from plone.memoize.instance import memoize
from Products.Five.browser import BrowserView

logger: Incomplete

class BaseInfoViewlet(BrowserView):
    __parent__: Incomplete
    view: Incomplete
    manager: Incomplete
    def __init__(self, context, request, view, manager) -> None: ...
    def update(self) -> None: ...
    def render(self) -> None: ...
    @property
    @memoize
    def policy(self): ...
    @memoize
    def created(self): ...
    @memoize
    def creator(self): ...
    @memoize
    def creator_url(self): ...
    @memoize
    def creator_name(self): ...
    @property
    @memoize
    def properties(self): ...
    def display_info_for_mtype(self, mtype):
        """get info for display of an mtype"""

class BaselineInfoViewlet(BaseInfoViewlet):
    index: Incomplete
    def render(self): ...
    @memoize
    def working_copy(self): ...

class CheckoutInfoViewlet(BaseInfoViewlet):
    index: Incomplete
    def render(self): ...
    @memoize
    def baseline(self): ...
