from _typeshed import Incomplete

class PreventTransactionCommit(Exception):
    reason: Incomplete
    def __init__(self, reason) -> None: ...

class UncommittableJar:
    """A jar that cannot be committed"""

    reason: Incomplete
    time: Incomplete
    def __init__(self, reason) -> None: ...
    def sortKey(self): ...
    def tpc_begin(self, *args) -> None: ...
    def commit(self, *args) -> None: ...
    def tpc_vote(self, transaction) -> None: ...
    def abort(*args) -> None: ...

class makeTransactionUncommittable:
    """
    - register an uncommittable object with the provided transaction
      which prevents the commit of that transaction
    """
    def __init__(self, transaction, reason) -> None: ...
