from _typeshed import Incomplete
from Acquisition import Implicit
from Persistence import Persistent

DEBUG: Incomplete
LOG: Incomplete

def TLOG(*args) -> None: ...

WRITEGRANULARITY: int

class TransientObject(Persistent, Implicit):
    """Dictionary-like object that supports additional methods
    concerning expiration and containment in a transient object container
    """

    security: Incomplete
    token: Incomplete
    id: Incomplete
    def __init__(self, containerkey) -> None: ...
    def getId(self): ...
    def invalidate(self) -> None: ...
    def isValid(self): ...
    def getLastAccessed(self): ...
    def setLastAccessed(self) -> None: ...
    def getLastModified(self): ...
    def setLastModified(self) -> None: ...
    def getCreated(self): ...
    def getContainerKey(self): ...
    def keys(self): ...
    def values(self): ...
    def items(self): ...
    def get(self, k, default=...): ...
    def __contains__(self, k) -> bool: ...
    has_key = __contains__
    def clear(self) -> None: ...
    def update(self, d) -> None: ...
    def __setitem__(self, k, v) -> None: ...
    def __getitem__(self, k): ...
    def __delitem__(self, k) -> None: ...
    set = __setitem__
    __guarded_setitem__ = __setitem__
    __guarded_delitem__ = __delitem__
    delete = __delitem__
    getName = getId

def lastmodified_sort(d1, d2):
    """sort dictionaries in descending order based on last mod time"""

def lastaccessed_sort(d1, d2):
    """sort dictionaries in descending order based on last access time"""
