from _typeshed import Incomplete

class DefaultFieldDeserializer:
    field: Incomplete
    context: Incomplete
    request: Incomplete
    def __init__(self, field, context, request) -> None: ...
    def __call__(self, value): ...

class TextLineFieldDeserializer(DefaultFieldDeserializer):
    def __call__(self, value): ...

class LinkTextLineFieldDeserializer(TextLineFieldDeserializer):
    def __call__(self, value): ...

class DatetimeFieldDeserializer(DefaultFieldDeserializer):
    def __call__(self, value): ...

class ChoiceFieldDeserializer(DefaultFieldDeserializer):
    def __call__(self, value): ...

class CollectionFieldDeserializer(DefaultFieldDeserializer):
    def __call__(self, value): ...

class DictFieldDeserializer(DefaultFieldDeserializer):
    def __call__(self, value): ...

class TimeFieldDeserializer(DefaultFieldDeserializer):
    def __call__(self, value): ...

class TimedeltaFieldDeserializer(DefaultFieldDeserializer):
    def __call__(self, value): ...

class NamedFieldDeserializer(DefaultFieldDeserializer):
    def __call__(self, value): ...

class RichTextFieldDeserializer(DefaultFieldDeserializer):
    def __call__(self, value): ...

class DecimalFieldDeserializer(DefaultFieldDeserializer):
    def __call__(self, value): ...
