class OrderingMixin:
    def handle_ordering(self, data) -> None: ...
    def reorderItems(self, obj_id, delta, subset_ids) -> None: ...
    def resortAllItemsInContext(self, sort_on, sort_order) -> None: ...
    def getOrdering(self): ...
