from _typeshed import Incomplete
from Products.Five import BrowserView

def is_language_independent(ob): ...

class BabelUtils(BrowserView):
    portal_url: Incomplete
    group: Incomplete
    def __init__(self, context, request) -> None: ...
    def getGroup(self): ...
    def getTranslatedLanguages(self): ...
    def getPortal(self): ...
    def objToTranslate(self): ...
    def gtenabled(self): ...
    def languages(self):
        """Deprecated"""
    def translated_languages(self): ...
    def current_language_name(self):
        """Get the current language native name"""
    def max_nr_of_buttons(self): ...

def multilingualMoveObject(content, language):
    """Move content object and its contained objects to a new language folder
    Also set the language on all the content moved

    """
