from _typeshed import Incomplete
from plone.app.querystring.vocabularies import CatalogVocabularyFactory

def untranslated_languages(context): ...
def translated_languages(context): ...
def translated_urls(context): ...
def deletable_languages(context): ...
def sort_key(language): ...

class AllContentLanguageVocabulary:
    """Vocabulary factory for all content languages in the portal."""
    def __call__(self, context): ...

AllContentLanguageVocabularyFactory: Incomplete

class AllAvailableLanguageVocabulary:
    """Vocabulary factory for all enabled languages in the portal."""
    def __call__(self, context): ...

AllAvailableLanguageVocabularyFactory: Incomplete

class RootCatalogVocabularyFactory(CatalogVocabularyFactory):
    """Catalog Vocabulary which always uses the site root"""
    def __call__(self, context, query=None): ...
