from zope.container.sample import SampleContainer

class KeyManager(SampleContainer):
    def __init__(self, keyring_size: int = 5) -> None: ...
    def clear(self, ring: str = "_system") -> None: ...
    def rotate(self, ring: str = "_system") -> None: ...
    def secret(self, ring: str = "_system"): ...
