from _typeshed import Incomplete
from OFS.SimpleItem import SimpleItem
from Products.Five.browser import BrowserView

class RuleAdding(SimpleItem, BrowserView):
    context: Incomplete
    request: Incomplete
    contentName: Incomplete
    id: str
    def __init__(self, context, request) -> None: ...
    def add(self, content) -> None:
        """Add the rule to the context"""
    def renderAddButton(self) -> None: ...
    def namesAccepted(self): ...
    def nameAllowed(self): ...
    def isSingleMenuItem(self): ...
    def addingInfo(self): ...
    def hasCustomAddView(self) -> None: ...
    def nextURL(self) -> None: ...

class RuleElementAdding(SimpleItem, BrowserView):
    context: Incomplete
    request: Incomplete
    contentName: Incomplete
    def __init__(self, context, request) -> None: ...
    def nextURL(self): ...
    def renderAddButton(self) -> None: ...
    def namesAccepted(self): ...
    def nameAllowed(self): ...
    def isSingleMenuItem(self): ...
    def addingInfo(self): ...
    def hasCustomAddView(self) -> None: ...

class RuleConditionAdding(RuleElementAdding):
    id: str
    def add(self, content) -> None:
        """Add the rule element to the context rule"""

class RuleActionAdding(RuleElementAdding):
    id: str
    def add(self, content) -> None:
        """Add the rule element to the context rule"""
