from _typeshed import Incomplete
from plone.memoize.instance import memoize
from Products.Five.browser import BrowserView

class ManageAssignments(BrowserView):
    """Manage contextual rule assignments"""

    template: Incomplete
    def __call__(self): ...
    def globally_enabled(self): ...
    @memoize
    def view_url(self): ...
    @memoize
    def type_name(self): ...
    @memoize
    def acquired_rules(self): ...
    @memoize
    def assigned_rules(self): ...
    def has_rules(self): ...
    def assignable_rules(self): ...
