from _typeshed import Incomplete
from Products.Five.browser import BrowserView

def get_trigger_class(trigger): ...

class ContentRulesControlPanel(BrowserView):
    """Manage rules in a the global rules container"""

    template: Incomplete
    def __call__(self): ...
    def authorize(self) -> None: ...
    def globally_disabled(self): ...
    def registeredRules(self): ...
    def ruleTypesToShow(self): ...
    def statesToShow(self): ...
    def delete_rule(self): ...
    def enable_rule(self): ...
    def disable_rule(self): ...
    def globally_disable(self): ...
    def globally_enable(self): ...
