from _typeshed import Incomplete
from plone.memoize.instance import memoize
from Products.Five.browser import BrowserView

class ManageElements(BrowserView):
    """Manage elements in a rule"""

    template: Incomplete
    view_url: Incomplete
    rule_title: Incomplete
    rule_description: Incomplete
    rule_stop: Incomplete
    rule_cascading: Incomplete
    rule_enabled: Incomplete
    def __call__(self): ...
    def authorize(self) -> None: ...
    @property
    def base_url(self): ...
    def rule_event(self): ...
    @memoize
    def actions(self): ...
    @memoize
    def conditions(self): ...
    def addable_conditions(self): ...
    def addable_actions(self): ...
    def assignments(self): ...
    def globally_assign(self) -> None: ...
