from _typeshed import Incomplete

def datetimelike_to_iso(value): ...
def json_compatible(value, context=None):
    """The json_compatible function converts any value to JSON compatible
    data when possible, raising a TypeError for unsupported values.
    This is done by using the IJsonCompatible converters.

    Be aware that adapting the value `None` will result in a component
    lookup error unless `None` is passed in as default value.
    Because of that the `json_compatible` helper method should always be
    used for converting values that may be None.
    """

def default_converter(value): ...
def decimal_converter(value): ...
def bytes_converter(value): ...
def list_converter(value): ...
def persistent_list_converter(value): ...
def tuple_converter(value): ...
def frozenset_converter(value): ...
def set_converter(value): ...
def dict_converter(value): ...
def persistent_mapping_converter(value): ...
def python_datetime_converter(value): ...
def zope_DateTime_converter(value): ...
def date_converter(value): ...
def time_converter(value): ...
def timedelta_converter(value): ...

class RichtextDXContextConverter:
    value: Incomplete
    context: Incomplete
    def __init__(self, value, context) -> None: ...
    def __call__(self): ...

def i18n_message_converter(value): ...
def missing_value_converter(value) -> None: ...
