from _typeshed import Incomplete

class ConversationSerializer:
    context: Incomplete
    request: Incomplete
    def __init__(self, context, request) -> None: ...
    def __call__(self): ...

class CommentSerializer:
    context: Incomplete
    request: Incomplete
    def __init__(self, context, request) -> None: ...
    def __call__(self, include_items: bool = True): ...
    def get_author_image(self, username=None): ...
