from _typeshed import Incomplete

def update_with_working_copy_info(context, result) -> None: ...
def get_allow_discussion_value(context, request, result) -> None: ...

class SerializeToJson:
    context: Incomplete
    request: Incomplete
    def __init__(self, context, request) -> None: ...
    def getVersion(self, version): ...
    def __call__(
        self, version=None, include_items: bool = True, include_expansion: bool = True
    ): ...
    def check_permission(self, permission_name, obj): ...

class SerializeFolderToJson(SerializeToJson):
    def __call__(
        self, version=None, include_items: bool = True, include_expansion: bool = True
    ): ...

class DexterityObjectPrimaryFieldTarget:
    context: Incomplete
    request: Incomplete
    def __init__(self, context, request) -> None: ...
    def __call__(self): ...
    def get_primary_field_name(self): ...
    def check_permission(self, permission_name, obj): ...

class LinkObjectPrimaryFieldTarget:
    context: Incomplete
    request: Incomplete
    def __init__(self, context, request) -> None: ...
    def __call__(self):
        """
        If user can edit Link object, do not return remoteUrl
        """
