from _typeshed import Incomplete

log: Incomplete

class DefaultFieldSerializer:
    context: Incomplete
    request: Incomplete
    field: Incomplete
    def __init__(self, field, context, request) -> None: ...
    def __call__(self): ...
    def get_value(self, default=None): ...

class ChoiceFieldSerializer(DefaultFieldSerializer):
    field: Incomplete
    def __call__(self): ...

class CollectionFieldSerializer(DefaultFieldSerializer):
    field: Incomplete
    def __call__(self): ...

class ImageFieldSerializer(DefaultFieldSerializer):
    def __call__(self): ...

class FileFieldSerializer(DefaultFieldSerializer):
    def __call__(self): ...

class RichttextFieldSerializer(DefaultFieldSerializer):
    def __call__(self): ...

class TextLineFieldSerializer(DefaultFieldSerializer):
    def __call__(self): ...

class DefaultPrimaryFieldTarget:
    context: Incomplete
    request: Incomplete
    field: Incomplete
    def __init__(self, field, context, request) -> None: ...
    def use_primary_field_target(self): ...
    def __call__(self) -> None: ...

class PrimaryFileFieldTarget(DefaultPrimaryFieldTarget):
    def __call__(self): ...

class DateTimeFieldSerializer(DefaultFieldSerializer):
    def get_value(self, default=None): ...
