from _typeshed import Incomplete

class BaseSerializer:
    context: Incomplete
    request: Incomplete
    def __init__(self, context, request) -> None: ...
    def __call__(self): ...

class SerializeGroupToJsonSummary(BaseSerializer): ...

class SerializeGroupToJson(BaseSerializer):
    def __call__(self): ...
