from _typeshed import Incomplete
from plone.memoize.instance import memoize
from Products.Five.browser import BrowserView

class WorkingCopyInfo(BrowserView):
    context: Incomplete
    ref: Incomplete
    def __init__(self, context) -> None: ...
    def get_working_copy_info(self): ...
    @property
    @memoize
    def policy(self): ...
    @memoize
    def working_copy(self): ...
    @memoize
    def baseline(self): ...
    @memoize
    def created(self): ...
    @memoize
    def creator(self): ...
    @memoize
    def creator_url(self): ...
    @memoize
    def creator_name(self): ...
    @property
    @memoize
    def properties(self): ...
