from _typeshed import Incomplete
from Products.Five import BrowserView

class ContentsBaseAction(BrowserView):
    success_msg: Incomplete
    failure_msg: Incomplete
    required_obj_permission: Incomplete
    @property
    def site(self): ...
    def objectTitle(self, obj): ...
    def protect(self) -> None: ...
    def json(self, data): ...
    def get_selection(self): ...
    def action(self, obj) -> None:
        """
        fill in this method to do action against each item in the selection
        """
    def finish(self) -> None: ...
    errors: Incomplete
    dest: Incomplete
    catalog: Incomplete
    mtool: Incomplete
    def __call__(self, keep_selection_order: bool = False): ...
    def message(self, missing=[]): ...

class FolderContentsView(BrowserView):
    def get_actions(self): ...
    @property
    def ignored_columns(self):
        """Return columns, which should be ignored in folder contents."""
    def get_columns(self): ...
    def get_thumb_scale(self): ...
    def default_page_types(self): ...
    @property
    def ignored_indexes(self): ...
    def get_indexes(self): ...
    def get_options(self): ...
    options: Incomplete
    def __call__(self): ...

class ContextInfo(BrowserView):
    attributes: Incomplete
    def __call__(self): ...
