from _typeshed import Incomplete

class EditingControlPanelAdapter:
    settings: Incomplete
    def __init__(self, context) -> None: ...
    def get_visible_ids(self): ...
    def set_visible_ids(self, value) -> None: ...
    def get_enable_link_integrity_checks(self): ...
    def set_enable_link_integrity_checks(self, value) -> None: ...
    def get_ext_editor(self): ...
    def set_ext_editor(self, value) -> None: ...
    def get_default_editor(self): ...
    def set_default_editor(self, value) -> None: ...
    def get_lock_on_ttw_edit(self): ...
    def set_lock_on_ttw_edit(self, value) -> None: ...
    visible_ids: Incomplete
    enable_link_integrity_checks: Incomplete
    ext_editor: Incomplete
    default_editor: Incomplete
    lock_on_ttw_edit: Incomplete
