from _typeshed import Incomplete

class FilterControlPanelAdapter:
    settings: Incomplete
    def __init__(self, context) -> None: ...
    def get_disable_filtering(self): ...
    def set_disable_filtering(self, value) -> None: ...
    def get_nasty_tags(self): ...
    def set_nasty_tags(self, value) -> None: ...
    def get_valid_tags(self): ...
    def set_valid_tags(self, value) -> None: ...
    def get_custom_attributes(self): ...
    def set_custom_attributes(self, value) -> None: ...
    custom_attributes: Incomplete
    valid_tags: Incomplete
    nasty_tags: Incomplete
    disable_filtering: Incomplete
