from _typeshed import Incomplete

class LanguageControlPanelAdapter:
    context: Incomplete
    settings: Incomplete
    def __init__(self, context) -> None: ...
    def get_default_language(self): ...
    def set_default_language(self, value) -> None: ...
    default_language: Incomplete
    def get_available_languages(self): ...
    def set_available_languages(self, value) -> None: ...
    available_languages: Incomplete
    def get_use_combined_language_codes(self): ...
    def set_use_combined_language_codes(self, value) -> None: ...
    use_combined_language_codes: Incomplete
    def get_display_flags(self): ...
    def set_display_flags(self, value) -> None: ...
    display_flags: Incomplete
    def get_always_show_selector(self): ...
    def set_always_show_selector(self, value) -> None: ...
    always_show_selector: Incomplete
    def get_use_content_negotiation(self): ...
    def set_use_content_negotiation(self, value) -> None: ...
    use_content_negotiation: Incomplete
    def get_use_path_negotiation(self): ...
    def set_use_path_negotiation(self, value) -> None: ...
    use_path_negotiation: Incomplete
    def get_use_cookie_negotiation(self): ...
    def set_use_cookie_negotiation(self, value) -> None: ...
    use_cookie_negotiation: Incomplete
    def get_authenticated_users_only(self): ...
    def set_authenticated_users_only(self, value) -> None: ...
    authenticated_users_only: Incomplete
    def get_set_cookie_always(self): ...
    def set_set_cookie_always(self, value) -> None: ...
    set_cookie_always: Incomplete
    def get_use_subdomain_negotiation(self): ...
    def set_use_subdomain_negotiation(self, value) -> None: ...
    use_subdomain_negotiation: Incomplete
    def get_use_cctld_negotiation(self): ...
    def set_use_cctld_negotiation(self, value) -> None: ...
    use_cctld_negotiation: Incomplete
    def get_use_request_negotiation(self): ...
    def set_use_request_negotiation(self, value) -> None: ...
    use_request_negotiation: Incomplete
