from _typeshed import Incomplete

class MailControlPanelAdapter:
    context: Incomplete
    portal: Incomplete
    encoding: str
    mail_settings: Incomplete
    def __init__(self, context) -> None: ...
    def get_smtp_host(self): ...
    def set_smtp_host(self, value) -> None: ...
    smtp_host: Incomplete
    def get_smtp_port(self): ...
    def set_smtp_port(self, value) -> None: ...
    smtp_port: Incomplete
    def get_smtp_userid(self): ...
    def set_smtp_userid(self, value) -> None: ...
    smtp_userid: Incomplete
    def get_smtp_pass(self): ...
    def set_smtp_pass(self, value) -> None: ...
    smtp_pass: Incomplete
    def get_email_from_name(self): ...
    def set_email_from_name(self, value) -> None: ...
    email_from_name: Incomplete
    def get_email_from_address(self): ...
    def set_email_from_address(self, value) -> None: ...
    email_from_address: Incomplete
