from _typeshed import Incomplete

class MarkupControlPanelAdapter:
    settings: Incomplete
    def __init__(self, context) -> None: ...
    @property
    def default_type(self): ...
    @default_type.setter
    def default_type(self, value) -> None: ...
    @property
    def allowed_types(self): ...
    @allowed_types.setter
    def allowed_types(self, value) -> None: ...
