from _typeshed import Incomplete

class NavigationControlPanelAdapter:
    context: Incomplete
    navigation_settings: Incomplete
    def __init__(self, context) -> None: ...
    def get_generate_tabs(self): ...
    def set_generate_tabs(self, value) -> None: ...
    generate_tabs: Incomplete
    def get_nonfolderish_tabs(self): ...
    def set_nonfolderish_tabs(self, value) -> None: ...
    nonfolderish_tabs: Incomplete
    def get_show_excluded_items(self): ...
    def set_show_excluded_items(self, value) -> None: ...
    show_excluded_items: Incomplete
    def get_displayed_types(self): ...
    def set_displayed_types(self, value) -> None: ...
    displayed_types: Incomplete
    def get_filter_on_workflow(self): ...
    def set_filter_on_workflow(self, value) -> None: ...
    filter_on_workflow: Incomplete
    def get_workflow_states_to_show(self): ...
    def set_workflow_states_to_show(self, value) -> None: ...
    workflow_states_to_show: Incomplete
    @property
    def root(self): ...
    @root.setter
    def root(self, value) -> None: ...
