from _typeshed import Incomplete

class SearchControlPanelAdapter:
    portal: Incomplete
    search_settings: Incomplete
    def __init__(self, context) -> None: ...
    def get_enable_livesearch(self): ...
    def set_enable_livesearch(self, value) -> None: ...
    enable_livesearch: Incomplete
    def get_types_not_searched(self): ...
    def set_types_not_searched(self, value) -> None: ...
    types_not_searched: Incomplete
    @property
    def sort_on(self): ...
    @sort_on.setter
    def sort_on(self, value) -> None: ...
