from _typeshed import Incomplete

class SecurityControlPanelAdapter:
    portal: Incomplete
    pmembership: Incomplete
    settings: Incomplete
    def __init__(self, context) -> None: ...
    def get_enable_self_reg(self): ...
    def set_enable_self_reg(self, value) -> None: ...
    enable_self_reg: Incomplete
    def get_enable_user_pwd_choice(self): ...
    def set_enable_user_pwd_choice(self, value) -> None: ...
    enable_user_pwd_choice: Incomplete
    def get_enable_user_folders(self): ...
    def set_enable_user_folders(self, value) -> None: ...
    enable_user_folders: Incomplete
    def get_allow_anon_views_about(self): ...
    def set_allow_anon_views_about(self, value) -> None: ...
    allow_anon_views_about: Incomplete
    def get_use_email_as_login(self): ...
    def set_use_email_as_login(self, value) -> None: ...
    use_email_as_login: Incomplete
    def get_use_uuid_as_userid(self): ...
    def set_use_uuid_as_userid(self, value) -> None: ...
    use_uuid_as_userid: Incomplete
