from _typeshed import Incomplete

class SiteControlPanelAdapter:
    settings: Incomplete
    def __init__(self, context) -> None: ...
    def get_site_title(self): ...
    def set_site_title(self, value) -> None: ...
    def get_webstats_js(self): ...
    def set_webstats_js(self, value) -> None: ...
    site_title: Incomplete
    webstats_js: Incomplete
    site_logo: Incomplete
    enable_sitemap: Incomplete
    exposeDCMetaTags: Incomplete
