from _typeshed import Incomplete

class UserGroupsSettingsControlPanelAdapter:
    context: Incomplete
    portal: Incomplete
    usergroups_settings: Incomplete
    def __init__(self, context) -> None: ...
    def get_many_groups(self): ...
    def set_many_groups(self, value) -> None: ...
    many_groups: Incomplete
    def get_many_users(self): ...
    def set_many_users(self, value) -> None: ...
    many_users: Incomplete
