from _typeshed import Incomplete
from persistent import Persistent

import plone.schema
import zope.schema
import zope.schema._field

HASPLONESCHEMA: bool

def is_primitive(value): ...

class DisallowedProperty:
    """A property that may not be set on an instance. It may still be set
    defined in a base class.
    """

    uses: Incomplete
    def __init__(self, name) -> None: ...
    def __get__(self, inst, type_=None): ...
    def __set__(self, inst, value) -> None: ...

class StubbornProperty:
    """A property that stays stubbornly at a single, pre-defined value."""

    uses: Incomplete
    def __init__(self, name, value) -> None: ...
    def __set__(self, inst, value) -> None: ...
    def __get__(self, inst, type_=None): ...

class InterfaceConstrainedProperty:
    """A property that may only contain values providing a certain interface."""

    uses: Incomplete
    def __init__(self, name, interface) -> None: ...
    def __set__(self, inst, value) -> None: ...

class PersistentField(Persistent):
    """Base class for persistent field definitions."""

    order: Incomplete
    constraint: Incomplete
    interfaceName: Incomplete
    fieldName: Incomplete

class PersistentCollectionField(PersistentField, zope.schema._field.AbstractCollection):
    """Ensure that value_type is a persistent field"""

    value_type: Incomplete

class Bytes(PersistentField, zope.schema.Bytes): ...
class BytesLine(PersistentField, zope.schema.BytesLine): ...
class ASCII(PersistentField, zope.schema.ASCII): ...
class ASCIILine(PersistentField, zope.schema.ASCIILine): ...
class Text(PersistentField, zope.schema.Text): ...
class TextLine(PersistentField, zope.schema.TextLine): ...
class Bool(PersistentField, zope.schema.Bool): ...
class Int(PersistentField, zope.schema.Int): ...
class Float(PersistentField, zope.schema.Float): ...
class Decimal(PersistentField, zope.schema.Decimal): ...
class Tuple(PersistentCollectionField, zope.schema.Tuple): ...
class List(PersistentCollectionField, zope.schema.List): ...
class Set(PersistentCollectionField, zope.schema.Set): ...
class FrozenSet(PersistentCollectionField, zope.schema.FrozenSet): ...
class Password(PersistentField, zope.schema.Password): ...

class Dict(PersistentField, zope.schema.Dict):
    key_type: Incomplete
    value_type: Incomplete

class Datetime(PersistentField, zope.schema.Datetime): ...
class Date(PersistentField, zope.schema.Date): ...
class Timedelta(PersistentField, zope.schema.Timedelta): ...
class SourceText(PersistentField, zope.schema.SourceText): ...
class URI(PersistentField, zope.schema.URI): ...
class Id(PersistentField, zope.schema.Id): ...
class DottedName(PersistentField, zope.schema.DottedName): ...

class Choice(PersistentField, zope.schema.Choice):
    vocabularyName: Incomplete
    def __init__(self, values=None, vocabulary=None, source=None, **kw) -> None: ...
    @property
    def vocabulary(self): ...
    def bind(self, object): ...

class JSONField(PersistentField, plone.schema.JSONField):
    key_type: Incomplete
    value_type: Incomplete
