from _typeshed import Incomplete
from collections.abc import MutableMapping

class RecordsProxy:
    """A proxy that maps an interface to a number of records"""
    def __init__(self, registry, schema, omitted=(), prefix=None) -> None: ...
    def __getattr__(self, name): ...
    def __setattr__(self, name, value) -> None: ...

class RecordsProxyCollection(MutableMapping):
    """A proxy that maps a collection of RecordsProxy objects"""

    registry: Incomplete
    schema: Incomplete
    check: Incomplete
    omitted: Incomplete
    prefix: Incomplete
    factory: Incomplete
    def __init__(
        self,
        registry,
        schema,
        check: bool = True,
        omitted=(),
        prefix=None,
        factory=None,
    ) -> None: ...
    def __getitem__(self, key): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def keys(self): ...
    def has_key(self, key): ...
    def add(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def setdefault(self, key, failobj=None): ...
    def __delitem__(self, key) -> None: ...
