from _typeshed import Incomplete
from persistent import Persistent

class Registry(Persistent):
    """The persistent registry"""
    def __init__(self) -> None: ...
    def __getitem__(self, name): ...
    def get(self, name, default=None): ...
    def __setitem__(self, name, value) -> None: ...
    def __contains__(self, name) -> bool: ...
    @property
    def records(self): ...
    def forInterface(
        self, interface, check: bool = True, omit=(), prefix=None, factory=None
    ): ...
    def registerInterface(self, interface, omit=(), prefix=None) -> None: ...
    def collectionOfInterface(
        self, interface, check: bool = True, omit=(), prefix=None, factory=None
    ): ...

class _Records:
    """The records stored in the registry. This implements dict-like access
    to records, where as the Registry object implements dict-like read-only
    access to values.
    """

    __parent__: Incomplete
    def __init__(self, parent) -> None: ...
    def __setitem__(self, name, record) -> None: ...
    def __delitem__(self, name) -> None: ...
    def __getitem__(self, name): ...
    def get(self, name, default=None): ...
    def __nonzero__(self): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def has_key(self, name): ...
    def __contains__(self, name) -> bool: ...
    def keys(self, min=None, max=None): ...
    def maxKey(self, key=None): ...
    def minKey(self, key=None): ...
    def values(self, min=None, max=None): ...
    def items(self, min=None, max=None): ...
    def setdefault(self, key, value): ...
    def clear(self) -> None: ...

class Records(_Records, Persistent):
    """BBB: This used to be the class for the _records attribute of the
    registry. Having this be a Persistent object was always a bad idea. We
    keep it here so that we can migrate to the new structure, but it should
    no longer be used.
    """
    def __init__(self, parent) -> None: ...
