from plone.rest import Service

class BaseService(Service):
    def render(self): ...

class Get(BaseService):
    def data(self): ...

class Post(BaseService):
    def data(self): ...

class Put(BaseService):
    def data(self): ...

class Delete(BaseService):
    def data(self): ...

class Patch(BaseService):
    def data(self): ...

class Options(BaseService):
    def data(self): ...

class NamedGet(BaseService):
    def data(self): ...

class NamedPost(BaseService):
    def data(self): ...

class NamedPut(BaseService):
    def data(self): ...

class NamedDelete(BaseService):
    def data(self): ...

class NamedPatch(BaseService):
    def data(self): ...

class NamedOptions(BaseService):
    def data(self): ...
