from _typeshed import Incomplete
from ZPublisher.BaseRequest import DefaultPublishTraverse

class RESTTraverse(DefaultPublishTraverse):
    def publishTraverse(self, request, name): ...
    def browserDefault(self, request): ...

class MarkAsRESTTraverser:
    """
    Traversal adapter for the ``++api++`` namespace.
    It marks the request as API request.
    """

    context: Incomplete
    request: Incomplete
    def __init__(self, context, request) -> None: ...
    def traverse(self, name_ignored, subpath_ignored): ...

class RESTWrapper:
    """A wrapper for objects traversed during a REST request."""

    context: Incomplete
    request: Incomplete
    def __init__(self, context, request) -> None: ...
    def __getattr__(self, name): ...
    def __getitem__(self, name): ...
    def __before_publishing_traverse__(self, arg1, arg2=None) -> None: ...
    def publishTraverse(self, request, name): ...
    def browserDefault(self, request): ...
