from _typeshed import Incomplete
from Products.Five.browser import BrowserView

logger: Incomplete

class FourOhFourView(BrowserView):
    def attempt_redirect(self): ...
    def find_redirect_if_view(self, old_path_elements, storage):
        """find redirect for urls like http://example.com/object/@@view/part."""
    def find_redirect_if_template(self, url, old_path_elements, storage): ...
    def find_first_parent(self): ...
    def search_for_similar(self): ...
