from persistent import Persistent

class RedirectionStorage(Persistent):
    """Stores old paths to new paths.

    Note - instead of storing "new paths" it could store object ids or
    similar. In general, there is a many-to-one relationship between
    "old paths" and "new paths". An "old path" points to exactly one
    "new path" (where the object is now to be found), but a "new path"
    can be pointed to by multiple different "old paths" (several objects
    that used to be distinct are now consolidated into one).

    See test_storage.py for demonstrations of its usage.
    """
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def add(self, old_path, new_path, now=None, manual: bool = False) -> None: ...
    __setitem__ = add
    def update(self, info, manual: bool = True) -> None: ...
    def remove(self, old_path) -> None: ...
    __delitem__ = remove
    def destroy(self, new_path) -> None: ...
    def has_path(self, old_path): ...
    __contains__ = has_path
    def get(self, old_path, default=None): ...
    def get_full(self, old_path, default=None): ...
    def __getitem__(self, old_path): ...
    def redirects(self, new_path): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
