from _typeshed import Incomplete
from plone.restapi.services import Service

class SourcesGet(Service):
    params: Incomplete
    def __init__(self, context, request) -> None: ...
    def publishTraverse(self, request, name): ...
    def reply(self): ...

def get_field_by_name(fieldname, context): ...
