from _typeshed import Incomplete

logger: Incomplete
FALLBACK_CONTENTTYPE: str

def SearchableText(obj): ...
def SearchableText_news(obj): ...
def SearchableText_document(obj): ...
def SearchableText_collection(obj): ...
def SearchableText_file(obj): ...
def SearchableText_link(obj): ...
def SearchableText_folder(obj): ...
def getRemoteUrl(obj): ...
def getObjSize_image(obj): ...
def getObjSize_file(obj): ...
def mime_type(obj): ...
def getIcon(obj):
    """
    geticon redefined in Plone > 5.0
    see https://github.com/plone/Products.CMFPlone/issues/1226

    reuse of metadata field,
    now used for showing thumbs in content listings etc.
    when obj is an image or has a lead image
    or has an image field with name 'image': true else false
    """
