from _typeshed import Incomplete

class UnorderedOrdering:
    """This implementation provides no ordering."""

    context: Incomplete
    def __init__(self, context) -> None: ...
    def notifyAdded(self, obj_id) -> None: ...
    def notifyRemoved(self, obj_id) -> None: ...
    def idsInOrder(self): ...
    def getObjectPosition(self, obj_id) -> None: ...
