from _typeshed import Incomplete

def attributeUUID(context): ...

class MutableAttributeUUID:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def get(self): ...
    def set(self, uuid) -> None: ...
