MAX_DESCRIPTION: int

def total_comments(object): ...
def last_comment_date(object): ...
def commentators(object): ...
def title(object): ...
def creator(object): ...
def description(object): ...
def searchable_text(object): ...
def in_response_to(object): ...
def effective(object): ...
def created(object): ...
def modified(object): ...
def comments_total_comments(object) -> None: ...
def comments_last_comment_date(object) -> None: ...
def comments_commentators(object) -> None: ...
def UID(object): ...
