from _typeshed import Incomplete
from Acquisition import Explicit
from collections.abc import Generator
from OFS.Traversable import Traversable
from persistent import Persistent

class Conversation(Traversable, Persistent, Explicit):
    """A conversation is a container for all comments on a content object.

    It manages internal data structures for comment threading and efficient
    comment lookup.
    """

    __allow_access_to_unprotected_subobjects__: bool
    id: Incomplete
    def __init__(self, id: str = "++conversation++default") -> None: ...
    def getId(self):
        """Get the id of the conversation. This is used to construct a
        URL.
        """
    def enabled(self): ...
    def total_comments(self): ...
    @property
    def last_comment_date(self): ...
    @property
    def commentators(self): ...
    @property
    def public_commentators(self): ...
    def objectIds(self): ...
    def getComments(self, start: int = 0, size=None) -> Generator[Incomplete]:
        """Get unthreaded comments"""
    def getThreads(
        self, start: int = 0, size=None, root: int = 0, depth=None
    ) -> Generator[Incomplete, Incomplete]:
        """Get threaded comments"""
    def addComment(self, comment):
        """Add a new comment. The parent id should have been set already. The
        comment id may be modified to find a free key. The id used will be
        returned.
        """
    def __len__(self) -> int: ...
    def __contains__(self, key) -> bool: ...
    def __getitem__(self, key):
        """Get an item by its int key"""
    def __delitem__(self, key, suppress_container_modified: bool = False) -> None:
        """Delete an item by its int key"""
    def __iter__(self): ...
    def get(self, key, default=None): ...
    def keys(self): ...
    def items(self): ...
    def values(self): ...
    def iterkeys(self): ...
    def itervalues(self) -> Generator[Incomplete]: ...
    def iteritems(self) -> Generator[Incomplete]: ...
    def allowedContentTypes(self): ...

def conversationAdapterFactory(content):
    """
    Adapter factory to fetch the default conversation from annotations.
    """

def conversationCanonicalAdapterFactory(content):
    """Adapter factory to fetch the default conversation from annotations.
    Will create the conversation if it does not exist.

    This adapter will fetch and store all comments on the canonical object,
    so that comments will be shared across all translations.
    """

class ConversationReplies:
    """An IReplies adapter for conversations.

    This makes it easy to work with top-level comments.
    """

    conversation: Incomplete
    comment_id: int
    def __init__(self, context) -> None: ...
    def addComment(self, comment): ...
    def __len__(self) -> int: ...
    def __contains__(self, key) -> bool: ...
    def __getitem__(self, key):
        """Get an item by its int key"""
    def __delitem__(self, key) -> None:
        """Delete an item by its int key"""
    def __iter__(self): ...
    def get(self, key, default=None): ...
    def keys(self): ...
    def items(self): ...
    def values(self): ...
    def iterkeys(self): ...
    def itervalues(self) -> Generator[Incomplete]: ...
    def iteritems(self) -> Generator[Incomplete]: ...
    @property
    def children(self): ...

class CommentReplies(ConversationReplies):
    """An IReplies adapter for comments.

    This makes it easy to work with replies to specific comments.
    """

    comment: Incomplete
    conversation: Incomplete
    comment_id: Incomplete
    def __init__(self, context) -> None: ...
    def addComment(self, comment): ...
