from _typeshed import Incomplete
from OFS.Folder import Folder

class ContainerTab(Folder):
    id: Incomplete
    def __init__(self, id) -> None: ...
    def getId(self): ...
    def manage_options(self): ...
    def manage_workspace(self, RESPONSE) -> None:
        """
        Redirects to the primary option.
        """
    def __getattr__(self, name): ...
    def get(self, name, default=None): ...
    def has_key(self, key): ...
    def objectIds(self, spec=None): ...
    def keys(self): ...
    def items(self): ...
    def values(self): ...
    def manage_renameObjects(self, ids=[], new_ids=[], REQUEST=None):
        """Rename several sub-objects"""
