from _typeshed import Incomplete
from zope.contentprovider.provider import ContentProviderBase

class ContentMenuProvider(ContentProviderBase):
    """Content menu provider for the "view" tab: displays the menu"""

    index: Incomplete
    def render(self): ...
    def available(self): ...
    def toolbar_position(self): ...
    def menu(self): ...
