from _typeshed import Incomplete
from Products.PluggableAuthService.UserPropertySheet import UserPropertySheet

class PropertyValueError(ValueError): ...

class PropertySchemaTypeMap:
    tmap: Incomplete
    tmap_order: Incomplete
    def __init__(self) -> None: ...
    def addType(self, type_name, identifier, order=None) -> None: ...
    def getTypeFor(self, value): ...
    def validate(self, property_type, value): ...

PropertySchema: Incomplete
validateValue: Incomplete

class MutablePropertySheet(UserPropertySheet):
    def validateProperty(self, id, value) -> None: ...
    def setProperty(self, user, id, value) -> None: ...
    def setProperties(self, user, mapping) -> None: ...

class SchemaMutablePropertySheet(MutablePropertySheet): ...
