from _typeshed import Incomplete

class ContentArchiver:
    context: Incomplete
    repository: Incomplete
    def __init__(self, context) -> None: ...
    def save(self, checkin_message) -> None: ...
    def isVersionable(self): ...
    def isVersioned(self): ...
    def isModified(self): ...
