from _typeshed import Incomplete

class CheckinCheckoutBasePolicyAdapter:
    """Base Checkin Checkout Policy For Content

    - on checkout context is the baseline
    - on checkin context is the working copy.

    """

    default_base_message: str
    context: Incomplete
    def __init__(self, context) -> None: ...
    def checkin(self, checkin_message) -> None: ...
    def checkout(self, container): ...
    def cancelCheckout(self): ...
    def getBaseline(self) -> None: ...
    def getWorkingCopy(self) -> None: ...
    def getProperties(self, obj, default=None): ...

class BaseContentCopier:
    context: Incomplete
    def __init__(self, context) -> None: ...
