class Subject:
    """
    The Subject field in Plone currently uses a utf-8 encoded string.
    When a catalog query tries to compare a unicode string from the
    parsedquery with existing utf-8 encoded string indexes unindexing
    will fail with a UnicodeDecodeError. To prevent this from happening
    we always encode the Subject query.

    XXX: As soon as Plone uses unicode for all indexes, this code can
    be removed.
    """
    def __call__(self, value): ...

class base:
    """DateIndex query modifier
    see Products.PluginIndexes.DateIndex.DateIndex.DateIndex._convert function
    """
    def __call__(self, value): ...

class Date(base): ...
class created(base): ...
class effective(base): ...
class end(base): ...
class expires(base): ...
class modified(base): ...
class start(base): ...
