def correctMapping(out, portal) -> None: ...
def updateTransform(out, portal, transform_id) -> None: ...
def installPortalTransforms(portal) -> None: ...
def setupPortalTransforms(context) -> None:
    """
    Setup PortalTransforms step.
    """
