from _typeshed import Incomplete
from plone.memoize import volatile as volatile
from plone.memoize.interfaces import ICacheChooser as ICacheChooser

global_cache: Incomplete
DontCache = volatile.DontCache
MARKER: Incomplete

class AbstractDict:
    def get(self, key, default=None): ...

class MemcacheAdapter(AbstractDict):
    client: Incomplete
    globalkey: Incomplete
    def __init__(self, client, globalkey: str = "") -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...

class RAMCacheAdapter(AbstractDict):
    ramcache: Incomplete
    globalkey: Incomplete
    def __init__(self, ramcache, globalkey: str = "") -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...

def choose_cache(fun_name): ...
def store_in_cache(fun, *args, **kwargs): ...
def cache(get_key): ...
