from _typeshed import Incomplete

class CleanupDict(dict):
    cleanup_period: Incomplete
    def __init__(self, cleanup_period=None) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...

ATTR: str
CONTAINER_FACTORY = CleanupDict

class DontCache(Exception): ...

def store_on_self(method, obj, *args, **kwargs): ...
def store_on_context(method, obj, *args, **kwargs): ...
def cache(get_key, get_cache=...): ...
