from OFS.SimpleItem import SimpleItem
from plone.contentrules.rule.rule import Rule as BaseRule

ANNOTATION_KEY: str

class Rule(SimpleItem, BaseRule):
    """A Zope 2 version of a rule, subject to acquisition, but otherwise
    identical.
    """
    @property
    def id(self): ...

def get_assignments(rule): ...
def insert_assignment(rule, path) -> None: ...
def rule_removed(rule, event) -> None: ...
def container_moved(container, event) -> None: ...
def container_removed(container, event) -> None: ...
