from _typeshed import Incomplete
from Products.PluggableAuthService.plugins.BasePlugin import BasePlugin
from Products.PluggableAuthService.PropertiedUser import PropertiedUser

manage_addAutoGroupForm: Incomplete

def manage_addAutoGroup(
    self, id, title: str = "", group: str = "", description: str = "", RESPONSE=None
):
    """Add an Auto Group plugin."""

class VirtualGroup(PropertiedUser):
    id: Incomplete
    title: Incomplete
    description: Incomplete
    def __init__(self, id, title: str = "", description: str = "") -> None: ...
    def getId(self): ...
    def getUserName(self): ...
    def getName(self): ...
    def getMemberIds(self, transitive: int = 1): ...
    def getRolesInContext(self, context): ...
    def getRoles(self): ...
    def allowed(self, object, object_roles=None): ...
    def getDomains(self): ...
    def isGroup(self): ...

class AutoGroup(BasePlugin):
    meta_type: str
    title: Incomplete
    group: Incomplete
    description: Incomplete
    def __init__(
        self, id, title: str = "", group=None, description: str = ""
    ) -> None: ...
    def enumerateGroups(
        self, id=None, exact_match: bool = False, sort_by=None, max_results=None, **kw
    ): ...
    def getGroupsForPrincipal(self, principal, request=None): ...
    def getGroupById(self, group_id): ...
    def getGroups(self): ...
    def getGroupIds(self): ...
    def getGroupMembers(self, group_id): ...
    def getPropertiesForUser(self, user, request=None): ...
