from _typeshed import Incomplete
from plone.restapi.services import Service

class GroupsDelete(Service):
    """Deletes a user."""

    params: Incomplete
    def __init__(self, context, request) -> None: ...
    def publishTraverse(self, request, name): ...
    @property
    def is_zope_manager(self): ...
    def reply(self): ...
