from _typeshed import Incomplete

class Cloner:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def __call__(self, obj) -> None: ...

class LanguageIndependentFieldsManager:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def has_independent_fields(self): ...
    def copy_relation(self, relation_value, target_language): ...
    def copy_fields(self, translation): ...
