from _typeshed import Incomplete

class Language:
    context: Incomplete
    def __init__(self, context) -> None: ...
    def get_language(self): ...
    def set_language(self, language) -> None: ...
