from _typeshed import Incomplete
from plone.restapi.services import Service

def fix_location_header(context, request) -> None: ...

class CommentsGet(Service):
    comment_id: Incomplete
    def publishTraverse(self, request, name): ...
    def reply(self): ...

class CommentsAdd(Service):
    comment_id: Incomplete
    def publishTraverse(self, request, name): ...
    def reply(self): ...

class CommentsUpdate(Service):
    comment_id: Incomplete
    def publishTraverse(self, request, name): ...
    def reply(self): ...

class CommentsDelete(Service):
    comment_id: Incomplete
    def publishTraverse(self, request, name): ...
    def reply(self): ...
