"""Partial stubs for :mod:`zope.interface.declarations`."""

from collections.abc import Callable
from typing import Any
from zope.interface import implementer as implementer
from zope.interface import provider as provider

class Declaration:
    def __init__(self, *interfaces: Any) -> None: ...
    def __add__(self, other: Any) -> Declaration: ...
    def __sub__(self, other: Any) -> Declaration: ...

class Implements(Declaration): ...
class Provides(Declaration): ...

class ObjectSpecificationDescriptor:
    def __get__(self, inst: Any, cls: Any = ...) -> Any: ...

def implementedBy(cls: type) -> Implements: ...
def providedBy(ob: object) -> Provides: ...
def directlyProvidedBy(object: object) -> Provides: ...
def directlyProvides(object: Any, *interfaces: Any) -> None: ...
def alsoProvides(object: Any, *interfaces: Any) -> None: ...
def noLongerProvides(object: Any, interface: Any) -> None: ...
def classImplements(cls: type, *interfaces: Any) -> None: ...
def classImplementsOnly(cls: type, *interfaces: Any) -> None: ...
def classProvides(*interfaces: Any) -> None: ...
def implementer_only(*interfaces: Any) -> Callable[[type], type]: ...
