"""Partial stubs for :mod:`zope.interface.interfaces`."""

from typing import Any
from zope.interface import Attribute
from zope.interface import Interface as Interface

class IElement(Interface):
    __name__ = Attribute("The object name.")
    __doc__ = Attribute("The object doc string.")

class IAttribute(IElement):
    interface = Attribute("The interface declaring the attribute.")

class IMethod(IAttribute):
    def getSignatureInfo(self) -> dict[str, Any]: ...
    def getSignatureString(self) -> str: ...

class ISpecification(Interface):
    def providedBy(self, object: object) -> bool: ...
    def implementedBy(self, class_: type) -> bool: ...
    def isOrExtends(self, other: Any) -> bool: ...
    def extends(self, other: Any, strict: bool = ...) -> bool: ...

class IInterface(ISpecification, IElement):
    """Interface objects themselves provide this."""

    def names(self, all: bool = ...) -> tuple[str, ...]: ...
    def __call__(self, object: Any, default: Any = ...) -> Any: ...

class IInterfaceDeclaration(Interface): ...
class IDeclaration(ISpecification): ...

class IObjectEvent(Interface):
    object = Attribute("The subject of the event.")

class ObjectEvent:
    object: Any

    def __init__(self, object: Any) -> None: ...

class IComponentLookup(Interface): ...
class IRegistered(IObjectEvent): ...
class IUnregistered(IObjectEvent): ...
