"""Partial stubs for :mod:`zope.interface.interface`."""

from typing import Any

class Element:
    __name__: str
    __doc__: str | None

    def __init__(self, name: str, doc: str = ...) -> None: ...
    def getTaggedValue(self, tag: str) -> Any: ...
    def queryTaggedValue(self, tag: str, default: Any = ...) -> Any: ...
    def setTaggedValue(self, tag: str, value: Any) -> None: ...
    def getTaggedValueTags(self) -> Any: ...

class Attribute(Element):
    interface: Any

class Method(Attribute):
    def getSignatureInfo(self) -> dict[str, Any]: ...
    def getSignatureString(self) -> str: ...

class Specification:
    def providedBy(self, ob: object) -> bool: ...
    def implementedBy(self, cls: type) -> bool: ...
    def isOrExtends(self, other: Any) -> bool: ...
    def extends(self, other: Any, strict: bool = ...) -> bool: ...

class InterfaceClass(Element, Specification):
    def __init__(
        self,
        name: str,
        bases: Any = ...,
        attrs: Any = ...,
        __doc__: str = ...,
        __module__: str = ...,
    ) -> None: ...
    def names(self, all: bool = ...) -> tuple[str, ...]: ...
    def namesAndDescriptions(self, all: bool = ...) -> Any: ...
    def __call__(self, obj: Any = ..., default: Any = ...) -> Any: ...

def invariant(call: Any) -> Any: ...
