from .interfaces import BrowserIdManagerErr as BrowserIdManagerErr
from .interfaces import SessionDataManagerErr as SessionDataManagerErr

def commit(note) -> None: ...
def install_browser_id_manager(app) -> None: ...
def install_session_data_manager(app) -> None: ...
def initialize(context) -> None: ...
