def markupRegistrySettings(context): ...
def getAllowedContentTypes():
    """Get a set of allowed MIME types."""

def getDefaultWysiwygEditor(): ...
def getAvailableWysiwygEditors(): ...
def getWysiwygEditor(member_editor, available_editors, default_editor): ...
