from _typeshed import Incomplete

class retransform:
    """abstract class for regex transforms (re.sub wrapper)"""

    inputs: Incomplete
    regexes: Incomplete
    def __init__(self, name, *args) -> None: ...
    def name(self): ...
    def addRegex(self, pat, repl) -> None: ...
    def convert(self, orig, data, **kwargs): ...
