from _typeshed import Incomplete
from zope.container.contained import Contained

class PortletAssignmentSettings(Contained):
    data: Incomplete
    def __init__(self) -> None: ...
    def __setitem__(self, name, value) -> None: ...
    def __delitem__(self, name) -> None: ...
    def __getitem__(self, name): ...
    def get(self, name, default=None): ...

def portletAssignmentSettingsFactory(context): ...
