from _typeshed import Incomplete
from Products.CMFCore.utils import getToolByName as getToolByName

class TinyMCESettingsGenerator:
    context: Incomplete
    request: Incomplete
    settings: Incomplete
    filter_settings: Incomplete
    nav_root: Incomplete
    nav_root_url: Incomplete
    def __init__(self, context, request) -> None: ...
    def get_theme(self): ...
    def get_content_css(self, style_css: str = ""): ...
    def get_style_format(self, txt, _type: str = "format", base=None): ...
    def get_styles(self, styles, _type: str = "format", base=None): ...
    def get_all_style_formats(self): ...
    def get_tiny_config(self): ...
