"""Partial stubs for :mod:`zope.schema`.

Schema fields are stubbed as classes (rather than collapsing to ``Any``).
Field-to-attribute *type inference* (``TextLine()`` -> ``str``) was a
``mypy-zope`` plugin feature that pure stubs cannot reproduce; the fields are
typed only as themselves here.
"""

from typing import Any

class ValidationError(Exception):
    """Raised when a value fails field validation."""

class Field:
    __name__: str

    def __init__(
        self,
        title: Any = ...,
        description: Any = ...,
        required: bool = ...,
        readonly: bool = ...,
        default: Any = ...,
        missing_value: Any = ...,
        *args: Any,
        **kwargs: Any,
    ) -> None: ...
    def validate(self, value: Any) -> None: ...
    def bind(self, object: Any) -> Field: ...

class Container(Field): ...
class Iterable(Container): ...
class Collection(Iterable): ...
class Orderable(Field): ...
class Bool(Field): ...
class Bytes(Field): ...
class BytesLine(Bytes): ...
class ASCII(Bytes): ...
class ASCIILine(ASCII): ...
class Text(Field): ...
class TextLine(Text): ...
class SourceText(Text): ...
class NativeString(Field): ...
class NativeStringLine(Field): ...
class Password(TextLine): ...
class URI(NativeStringLine): ...
class Id(NativeStringLine): ...
class DottedName(NativeStringLine): ...
class Int(Orderable): ...
class Float(Orderable): ...
class Decimal(Orderable): ...
class Datetime(Orderable): ...
class Date(Orderable): ...
class Time(Orderable): ...
class Timedelta(Orderable): ...
class Choice(Field): ...
class List(Collection): ...
class Tuple(Collection): ...
class Set(Collection): ...
class FrozenSet(Collection): ...
class Dict(Collection): ...
class Object(Field): ...
class InterfaceField(Field): ...
