"""Partial stubs for :mod:`zope.schema._field` — the concrete field types.

``zope.schema`` re-exports every field from here; the public names live in
``zope.schema`` as well. Field-to-attribute *type inference* (a ``TextLine``
field becoming a ``str`` attribute on the implementing class) was a
``mypy-zope`` plugin feature and is intentionally not reproduced.
"""

from collections.abc import Callable
from typing import Any

class Field:
    __name__: str
    title: str
    description: str
    required: bool
    readonly: bool
    default: Any
    missing_value: Any

    def __init__(
        self,
        title: str = ...,
        description: str = ...,
        __name__: str = ...,
        required: bool = ...,
        readonly: bool = ...,
        constraint: Callable[[Any], bool] | None = ...,
        default: Any = ...,
        defaultFactory: Callable[[], Any] | None = ...,
        missing_value: Any = ...,
        **kwargs: Any,
    ) -> None: ...
    def validate(self, value: Any) -> None: ...
    def bind(self, object: Any) -> Field: ...
    def constraint(self, value: Any) -> bool: ...

class Orderable:
    min: Any
    max: Any

    def __init__(self, min: Any = ..., max: Any = ..., **kwargs: Any) -> None: ...

class MinMaxLen:
    min_length: int
    max_length: int | None

    def __init__(
        self, min_length: int = ..., max_length: int | None = ..., **kwargs: Any
    ) -> None: ...

class Bool(Field): ...
class Bytes(MinMaxLen, Field): ...
class BytesLine(Bytes): ...
class ASCII(Bytes): ...
class ASCIILine(ASCII): ...
class Text(MinMaxLen, Field): ...
class TextLine(Text): ...
class SourceText(Text): ...
class NativeString(Field): ...
class NativeStringLine(Field): ...
class Password(TextLine): ...
class URI(NativeStringLine): ...
class Id(NativeStringLine): ...

class DottedName(NativeStringLine):
    def __init__(
        self, *args: Any, min_dots: int = ..., max_dots: int | None = ..., **kwargs: Any
    ) -> None: ...

class Int(Orderable, Field): ...
class Float(Orderable, Field): ...
class Decimal(Orderable, Field): ...
class Datetime(Orderable, Field): ...
class Date(Orderable, Field): ...
class Time(Orderable, Field): ...
class Timedelta(Orderable, Field): ...
class InterfaceField(Field): ...

class Choice(Field):
    def __init__(
        self,
        values: Any = ...,
        vocabulary: Any = ...,
        source: Any = ...,
        **kwargs: Any,
    ) -> None: ...

class Container(Field): ...
class Iterable(Container): ...

class Collection(MinMaxLen, Iterable):
    value_type: Field | None
    unique: bool

    def __init__(
        self,
        value_type: Field | None = ...,
        unique: bool = ...,
        **kwargs: Any,
    ) -> None: ...

class Sequence(Collection): ...
class Tuple(Sequence): ...
class List(Sequence): ...
class Set(Collection): ...
class FrozenSet(Collection): ...

class Mapping(MinMaxLen, Field):
    key_type: Field | None
    value_type: Field | None

    def __init__(
        self,
        key_type: Field | None = ...,
        value_type: Field | None = ...,
        **kwargs: Any,
    ) -> None: ...

class Dict(Mapping): ...

class Object(Field):
    schema: Any

    def __init__(
        self, schema: Any = ..., validate_invariants: bool = ..., **kwargs: Any
    ) -> None: ...
