"""Partial stubs for :mod:`zope.schema.interfaces`."""

from zope.interface import Attribute
from zope.interface import Interface
from zope.interface import Invalid

class ValidationError(Invalid):
    """Raised when a value does not satisfy a field's constraints."""

class StopValidation(Exception): ...
class RequiredMissing(ValidationError): ...
class WrongType(ValidationError): ...
class ConstraintNotSatisfied(ValidationError): ...
class NotAContainer(ValidationError): ...
class NotAnIterator(ValidationError): ...
class WrongContainedType(ValidationError): ...
class SchemaNotProvided(ValidationError): ...
class TooBig(ValidationError): ...
class TooSmall(ValidationError): ...
class TooLong(ValidationError): ...
class TooShort(ValidationError): ...
class InvalidValue(ValidationError): ...
class InvalidDottedName(ValidationError): ...
class InvalidURI(ValidationError): ...
class InvalidId(ValidationError): ...
class IField(Interface): ...
class IBool(IField): ...
class IBytes(IField): ...
class IBytesLine(IBytes): ...
class IASCII(IBytes): ...
class IASCIILine(IASCII): ...
class IText(IField): ...
class ITextLine(IText): ...
class ISourceText(IText): ...
class INativeString(IField): ...
class INativeStringLine(IField): ...
class IPassword(ITextLine): ...
class IURI(INativeStringLine): ...
class IId(INativeStringLine): ...
class IDottedName(INativeStringLine): ...
class IInt(IField): ...
class IFloat(IField): ...
class IDecimal(IField): ...
class IDatetime(IField): ...
class IDate(IField): ...
class ITime(IField): ...
class ITimedelta(IField): ...
class IInterfaceField(IField): ...
class IChoice(IField): ...
class ICollection(IField): ...
class ISequence(ICollection): ...
class IList(ISequence): ...
class ITuple(ISequence): ...
class ISet(ICollection): ...
class IFrozenSet(ICollection): ...
class IMapping(IField): ...
class IDict(IMapping): ...
class IObject(IField): ...

class ITerm(Interface):
    value = Attribute("The value (object) represented by the term.")

class ITokenizedTerm(ITerm):
    token = Attribute("The token, a 7-bit ASCII string.")

class IVocabulary(Interface): ...
class IVocabularyTokenized(IVocabulary): ...
class IBaseVocabulary(IVocabulary): ...

class IVocabularyFactory(Interface):
    def __call__(self, context: object): ...
