"""Partial stubs for :mod:`zope.schema.vocabulary`."""

from collections.abc import Iterator
from typing import Any

class SimpleTerm:
    value: Any
    token: str
    title: str | None

    def __init__(self, value: Any, token: Any = ..., title: Any = ...) -> None: ...

class SimpleVocabulary:
    def __init__(self, terms: Any, *interfaces: Any, **kwargs: Any) -> None: ...
    @classmethod
    def fromValues(cls, values: Any, *interfaces: Any) -> SimpleVocabulary: ...
    @classmethod
    def fromItems(cls, items: Any, *interfaces: Any) -> SimpleVocabulary: ...
    @classmethod
    def createTerm(cls, *args: Any) -> SimpleTerm: ...
    def getTerm(self, value: Any) -> SimpleTerm: ...
    def getTermByToken(self, token: str) -> SimpleTerm: ...
    def __iter__(self) -> Iterator[SimpleTerm]: ...
    def __len__(self) -> int: ...
    def __contains__(self, value: Any) -> bool: ...

def getVocabularyRegistry() -> Any: ...
