from _typeshed import Incomplete
from persistent import Persistent
from zope.component.factory import Factory

class DexterityFactory(Persistent, Factory):
    """A factory for Dexterity content."""

    portal_type: Incomplete
    def __init__(self, portal_type) -> None: ...
    @property
    def title(self): ...
    @property
    def description(self): ...
    def __call__(self, *args, **kw): ...
    def getInterfaces(self): ...
