from _typeshed import Incomplete

def interfaceStringCheck(f): ...
def mark(ob, interface) -> None: ...
def erase(ob, interface) -> None: ...

mark: Incomplete
erase: Incomplete

class MarkerInterfacesAdapter:
    mark: Incomplete
    erase: Incomplete
    context: Incomplete
    def __init__(self, context) -> None: ...
    def dottedToInterfaces(self, seq): ...
    def getDirectlyProvided(self): ...
    def getDirectlyProvidedNames(self): ...
    def getAvailableInterfaces(self): ...
    def getAvailableInterfaceNames(self): ...
    def getInterfaces(self): ...
    def getInterfaceNames(self): ...
    def getProvided(self): ...
    def getProvidedNames(self): ...
    def update(self, add=(), remove=()) -> None:
        """Currently update adds and then removes, rendering duplicate null."""
