from _typeshed import Incomplete
from plone.memoize.view import memoize
from Products.Five.browser import BrowserView

BLACKLISTED_PROVIDERS: Incomplete
BLACKLISTED_CATEGORIES: Incomplete

class ContextState(BrowserView):
    """Information about the state of the current context"""
    @memoize
    def current_page_url(self): ...
    @memoize
    def current_base_url(self): ...
    @memoize
    def canonical_object(self): ...
    @memoize
    def canonical_object_url(self): ...
    @memoize
    def view_url(self):
        """URL to use for viewing

        Files and Images get downloaded when they are directly
        called, instead of with /view appended.  We want to avoid that.
        """
    @memoize
    def view_template_id(self): ...
    @memoize
    def is_view_template(self): ...
    @memoize
    def object_url(self): ...
    @memoize
    def object_title(self): ...
    @memoize
    def workflow_state(self): ...
    def parent(self): ...
    @memoize
    def folder(self): ...
    @memoize
    def is_folderish(self): ...
    @memoize
    def is_structural_folder(self): ...
    @memoize
    def is_default_page(self): ...
    @memoize
    def is_portal_root(self): ...
    @memoize
    def is_navigation_root(self): ...
    @memoize
    def is_editable(self): ...
    @memoize
    def is_locked(self): ...
    @memoize
    def is_toolbar_visible(self): ...
    @memoize
    def actions(self, category=None, max: int = -1): ...
    def portlet_assignable(self): ...
