from _typeshed import Incomplete
from plone.memoize.view import memoize
from plone.memoize.view import memoize_contextless
from Products.Five.browser import BrowserView

RIGHT_TO_LEFT: Incomplete

class PortalState(BrowserView):
    """Information about the state of the portal"""
    @memoize_contextless
    def portal(self): ...
    @memoize_contextless
    def portal_title(self): ...
    @memoize_contextless
    def portal_url(self): ...
    @memoize
    def navigation_root(self): ...
    @memoize
    def navigation_root_title(self): ...
    @memoize
    def navigation_root_path(self): ...
    @memoize
    def navigation_root_url(self): ...
    @memoize_contextless
    def default_language(self): ...
    def language(self): ...
    def locale(self): ...
    def is_rtl(self): ...
    @memoize_contextless
    def member(self): ...
    @memoize_contextless
    def anonymous(self): ...
    @memoize_contextless
    def friendly_types(self): ...
