from plone.memoize.view import memoize_contextless
from Products.Five.browser import BrowserView

class Tools(BrowserView):
    """Common tools"""
    @memoize_contextless
    def actions(self): ...
    @memoize_contextless
    def catalog(self): ...
    @memoize_contextless
    def membership(self): ...
    @memoize_contextless
    def url(self): ...
    @memoize_contextless
    def types(self): ...
    @memoize_contextless
    def workflow(self): ...
