from _typeshed import Incomplete

logger: Incomplete

def cleanup_resources() -> None: ...
def migrate_gopipindex(context) -> None: ...
def rebuild_memberdata(context) -> None: ...
def fix_core_behaviors_in_ftis(context) -> None: ...
def to52alpha1(context) -> None: ...
